/**
 * Extract Session Memories Edge Function
 * 
 * Post-session (after generate-coach-summary): creates discrete memory
 * entries in coach_memory_index from session summary data.
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { verifyAuth0JWT } from "../_shared/auth.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const verifiedUserId = await verifyAuth0JWT(req.headers.get('Authorization'));
    const { sessionId, userId } = await req.json();

    if (verifiedUserId !== userId) {
      return new Response(JSON.stringify({ error: 'User mismatch' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    );

    // Fetch the session summary (generated by generate-coach-summary)
    const { data: summary, error: summaryError } = await supabase
      .from('coach_session_summaries')
      .select('*')
      .eq('session_id', sessionId)
      .single();

    if (summaryError || !summary) {
      console.log('[extract-session-memories] No summary found for session:', sessionId);
      return new Response(JSON.stringify({ success: true, memoriesCreated: 0, message: 'No summary available' }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      });
    }

    const memories: Array<{
      user_id: string;
      session_id: string;
      memory_type: string;
      memory_content: string;
      memory_context: string;
      importance_score: number;
      pattern_area: string | null;
      key_themes: string[];
    }> = [];

    // Create memory entries from commitments
    for (const commitment of (summary.commitments_made || [])) {
      memories.push({
        user_id: userId,
        session_id: sessionId,
        memory_type: 'commitment',
        memory_content: commitment,
        memory_context: `Committed during session on ${new Date(summary.created_at).toLocaleDateString()}`,
        importance_score: 8,
        pattern_area: summary.dominant_pattern,
        key_themes: summary.key_topics || [],
      });
    }

    // Create memory entry from breakthrough
    if (summary.breakthrough_moment) {
      memories.push({
        user_id: userId,
        session_id: sessionId,
        memory_type: 'breakthrough',
        memory_content: summary.breakthrough_moment,
        memory_context: `Breakthrough during ${summary.emotional_arc || 'session'}`,
        importance_score: 10,
        pattern_area: summary.dominant_pattern,
        key_themes: summary.key_topics || [],
      });
    }

    // Create memory entry from session summary itself
    memories.push({
      user_id: userId,
      session_id: sessionId,
      memory_type: 'session_summary',
      memory_content: summary.summary_text,
      memory_context: `Session focused on ${(summary.key_topics || []).join(', ')}`,
      importance_score: 6,
      pattern_area: summary.dominant_pattern,
      key_themes: summary.key_topics || [],
    });

    // Create memory entries for practices
    for (const practice of (summary.practices_recommended || [])) {
      memories.push({
        user_id: userId,
        session_id: sessionId,
        memory_type: 'practice_feedback',
        memory_content: `Recommended: ${practice}`,
        memory_context: `During ${summary.dominant_pattern || 'general'} session`,
        importance_score: 5,
        pattern_area: summary.dominant_pattern,
        key_themes: summary.key_topics || [],
      });
    }

    // Insert all memories
    if (memories.length > 0) {
      const { error: insertError } = await supabase
        .from('coach_memory_index')
        .insert(memories);

      if (insertError) {
        console.error('[extract-session-memories] Insert error:', insertError);
      }
    }

    console.log(`[extract-session-memories] Created ${memories.length} memories for session ${sessionId}`);

    return new Response(JSON.stringify({ 
      success: true, 
      memoriesCreated: memories.length 
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });

  } catch (error: unknown) {
    console.error('[extract-session-memories] Error:', error);
    const message = error instanceof Error ? error.message : 'Unknown error';
    return new Response(JSON.stringify({ error: message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' }
    });
  }
});
