// Comprehensive content library for seeding (without image imports)
export const seedContent = [
  // ============= SOUNDBATHS =============
  
  // POWER-UP Soundbaths
  {
    id: "energised-focus-didgeridoo-bowls",
    title: "Bazaar Sound Journey with Didgeridoo & Bowls",
    contentType: "soundbath",
    category: "power-up",
    duration: 2.47,
    creator: "Didgeridoo traditions and harmonic bowl practices",
    origin: "Feel the pulse of the crowd, the breath of the didgeridoo, and the shimmering bowls guiding your mind from raw energy to sharp clarity.",
    storyHook: "Ancient didgeridoo + Himalayan bowls: raw energy refined into laser-sharp focus.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/67bda649-edbb-4f39-8290-175122fe99bf.png",
    audioSrc: "/soundscapes/didgeridoo-bowls.mp3",
    tags: ['fire', 'focus', 'moderate', 'energy', 'activation'],
    steps: 0,
    fullStory: "On ancient Australian plains, the didgeridoo's deep drone stirred courage, balance, and healing. In Himalayan monasteries, bowls were forged to refine the mind with clear, rising tones. True preparation isn't stillness or adrenaline—it is energy with direction. The didgeridoo gives the power; the bowls give the aim. Together, they move you from the body's ancient rhythms to the mind's highest clarity—not to relax you, but to prepare you.\n\nRitual of Use\n\nBefore the challenge — press play.\nClose your eyes.\nLet the rhythm seize you until hesitation dissolves.\nWhen it ends: act.",
    technique: "This is a two-phase practice. Phase 1 (Didgeridoo): Feel the low frequencies in your body—your chest, your belly, your legs. Don't just hear it; let it vibrate through you. This awakens your core energy and vitality. Phase 2 (Singing Bowls): As the bowls enter, feel the energy shift upward—into your heart, your throat, your head. The raw power becomes refined focus. Breathe deeply throughout. This isn't relaxation—it's energized presence. You're learning to transform primal momentum into laser-sharp attention.",
    benefits: [
      "Awakens core vitality and physical energy",
      "Channels raw energy into precise mental focus",
      "Sustains attention with energized presence",
      "Balances activation with calm clarity",
      "Builds capacity for high-intensity concentration"
    ],
    completionQuote: "True focus is not stillness—it is energy with direction. Power without presence is chaos; presence without power is passive."
  },
  {
    id: "warrior-drums",
    title: "Warrior Drums Activation",
    contentType: "soundbath",
    category: "power-up",
    duration: 3.5,
    creator: "Ancient warrior drum traditions",
    origin: "Primal drums from ancient battlefields",
    storyHook: "Primal drums from ancient battlefields—transform hesitation into decisive readiness.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/warrior-drums-hero.jpg",
    audioSrc: "/soundscapes/warrior-drums.mp3",
    tags: ['fire', 'pre-meeting', 'intense', 'power', 'courage'],
    steps: 0
  },
  {
    id: "basque-txalaparta",
    title: "Basque Txalaparta — Ancient Wooden Pulse for Presence",
    contentType: "soundbath",
    category: "power-up",
    duration: 4.25,
    creator: "Basque Txalaparta tradition",
    storyHook: "Ancient Basque wooden percussion—transform chaos into grounded presence.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/basque-txalaparta-hero.jpg",
    audioSrc: "/soundscapes/basque-txalaparta.mp3",
    tags: ['wood', 'grounding', 'presence'],
    steps: 0
  },
  
  // PAUSE Soundbaths
  {
    id: "harmonic-calm",
    title: "Deep Rest & Grounding with Harmonic Calm",
    contentType: "soundbath",
    category: "pause",
    duration: 3,
    creator: "Tibetan Buddhist singing bowl traditions",
    origin: "Tibetan Buddhist singing bowl traditions",
    storyHook: "Ancient Tibetan singing bowls create harmonic resonance for deep rest, nervous system regulation, and grounded presence.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/c72cc661-d2db-48b0-b39a-d5c4bb2253d3.png",
    audioSrc: "/soundscapes/harmonic-calm.mp3",
    tags: ['earth', 'post-stress', 'gentle', 'healing', 'meditation'],
    steps: 0,
    fullStory: "For over a thousand years, Tibetan Buddhist monks have used singing bowls as sacred instruments for meditation and healing. These bronze bowls, traditionally crafted in the Himalayan regions, produce harmonic overtones that are believed to align the body's energy centers and quiet the restless mind.",
    technique: "Find a comfortable seated or lying position. Close your eyes and allow your body to settle. As the singing bowls begin, notice how the sound waves seem to move through your body rather than just your ears. Don't try to control your thoughts—simply let the harmonic frequencies wash over you like gentle waves.",
    benefits: [
      "Reduces stress and anxiety through harmonic resonance",
      "Restores emotional balance and inner stability",
      "Cultivates deep relaxation and nervous system regulation",
      "Anchors attention in present-moment awareness",
      "Promotes grounded presence and mental clarity"
    ],
    completionQuote: "In stillness, the mind finds its natural harmony. Like ripples on a pond, thoughts settle into peace."
  },
  {
    id: "deep-calm-forest-bathing",
    title: "Deep Calm Forest Bathing",
    contentType: "soundbath",
    category: "pause",
    duration: 2,
    creator: "Japanese Shinrin-yoku practices",
    origin: "Japanese Shinrin-yoku (forest bathing) practices",
    storyHook: "Used to cultivate deep calm, restore mental clarity, and anchor attention in the present through gentle rain and subtle village sounds.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/f0c69073-c184-4d25-baaa-c8e5d07cfbd9.png",
    audioSrc: "/soundscapes/forest-bathing.mp3",
    tags: ['earth', 'nature', 'gentle', 'stress-relief', 'grounding'],
    steps: 0
  },
  {
    id: "monastic-resonance",
    title: "Monastic Resonance — Sacred Bells for Deep Pause",
    contentType: "soundbath",
    category: "pause",
    duration: 5.0,
    creator: "Monastic bell traditions",
    storyHook: "Sacred monastery bells—signal the mind to pause and reset.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/monastic-resonance-hero.jpg",
    audioSrc: "/soundscapes/monastic-resonance.mp3",
    tags: ['metal', 'meditation', 'pause'],
    steps: 0
  },
  
  // PRESENCE Soundbaths
  {
    id: "deep-focus-monastic-resonance-alt",
    title: "Deep Focus with Monastic Resonance",
    contentType: "soundbath",
    category: "presence",
    duration: 1.5,
    creator: "Monastic chanting and harmonic rituals",
    origin: "Monastic chanting and harmonic rituals in Himalayan-style summit monasteries",
    storyHook: "Used to sharpen cognitive clarity, sustain deep focus, and expand awareness through layered chants, resonant gongs, and ethereal chimes.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/monastic-resonance-hero.jpg",
    audioSrc: "/soundscapes/monastic-resonance.mp3",
    tags: ['air', 'focus', 'moderate', 'meditation', 'clarity'],
    steps: 0
  },
  {
    id: "sustained-focus-choir-harmonic",
    title: "Sustained Focus with Choir Harmonic",
    contentType: "soundbath",
    category: "presence",
    duration: 3.5,
    creator: "Sacred harmonic compositions",
    origin: "Sacred harmonic compositions in grand cathedrals",
    storyHook: "Used to enhance focus, cultivate mindful presence, and align energy through layered choirs, bells, and reverberant harmonics.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/afddfc0a-07c8-4659-bfb5-560d510b12c3.png",
    audioSrc: "/soundscapes/cathedral-choir-flow.mp3",
    tags: ['air', 'focus', 'moderate', 'sacred', 'resonance'],
    steps: 0
  },
  {
    id: "ina-night-fields",
    title: "Ina Night Fields (Tsukiyomi)",
    contentType: "soundbath",
    category: "presence",
    duration: 42,
    creator: "Natural field recording",
    origin: "Nagano Countryside, Japan",
    storyHook: "In the quiet heart of Nagano's countryside, where the land folds gently into mist and memory, night hums in perfect rhythm.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/aa4d150b-e5fe-48d7-aa74-9f082d21ffaa.png",
    audioSrc: "/soundscapes/ina-night-fields.mp3",
    tags: ['water', 'nature', 'gentle', 'evening', 'ambient'],
    steps: 0
  },
  {
    id: "earth-resonance",
    title: "Earth Resonance — Deep Grounding Frequencies",
    contentType: "soundbath",
    category: "presence",
    duration: 4.5,
    creator: "Schumann resonance-inspired soundscape",
    origin: "Earth's natural electromagnetic frequencies",
    storyHook: "Align with the Earth's natural pulse for deep grounding and centered presence.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/4ed33e6d-77b9-47f9-9981-bab218507307.png",
    audioSrc: "/soundscapes/earth-resonance.mp3",
    tags: ['earth', 'grounding', 'resonance', 'nature'],
    steps: 0
  },
  {
    id: "tibetan-bowls",
    title: "Tibetan Singing Bowls — Pure Harmonic Resonance",
    contentType: "soundbath",
    category: "pause",
    duration: 5.5,
    creator: "Traditional Tibetan bowl masters",
    origin: "Ancient Himalayan healing traditions",
    storyHook: "Pure crystal-clear tones that calm the nervous system and restore balance.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/06444f60-b3bd-4d38-a749-aea185d789e6.png",
    audioSrc: "/soundscapes/tibetan-bowls.mp3",
    tags: ['metal', 'meditation', 'healing', 'calm'],
    steps: 0
  },
  
  // ============= GUIDED PRACTICES =============
  
  // POWER-UP Practices
  {
    id: "kapalabhati-pranayama",
    title: "Energy Surge Through Kapalabhati Pranayama",
    contentType: "guided-practice",
    category: "power-up",
    duration: 6,
    difficulty: "intermediate",
    origin: "Ancient Yogic Energizing Breath",
    storyHook: "Ancient yogic 'skull shining' breath—instant vitality and mental clarity.",
    usedBy: "Yogis, Warriors, High Performers",
    thumbnail: "/lovable-uploads/7a5dd5f2-96fb-485c-a58f-0280491740c1.png",
    audioSrc: "/soundscapes/kapalabhati-pranayama.mp3",
    creator: "Ancient Yogic Energizing Breath",
    voice: "female",
    language: "en",
    tags: ['fire', 'energy-boost', 'intense', 'morning', 'breathwork'],
    steps: 6,
    fullStory: "Kapalabhati, meaning 'skull shining' in Sanskrit, is an ancient yogic cleansing technique from the Hatha Yoga Pradipika. Yogis discovered that rapid, forceful exhalations generate immediate vitality and mental clarity.",
    technique: "Sharp, forceful exhales through the nose while the belly contracts. The inhale is passive and automatic. Start with 30 breaths, build to 100. End each round with a breath hold.",
    benefits: [
      "Immediate surge of energy and vitality",
      "Complete mental clarity and alertness",
      "Feeling of internal heat and activation",
      "Increased lung capacity and respiratory health",
      "Stronger core muscles",
      "Enhanced metabolic rate"
    ],
    completionQuote: "Your skull is shining. Your fire is lit. You are fully activated.",
    whatYouNeed: [
      "⚠️ DO NOT PRACTICE IF: Pregnant, heart disease, high blood pressure",
      "Essential: Empty stomach (at least 2 hours after eating)",
      "Essential: Comfortable seated position with straight spine"
    ],
    expectedOutcomes: [
      "Immediate: Surge of energy and vitality",
      "Regular Practice: Significantly increased energy levels"
    ]
  },
  {
    id: "box-breathing",
    title: "Combat Breathing — Box Breathing for Instant Calm Under Pressure",
    contentType: "guided-practice",
    category: "pause",
    duration: 4,
    difficulty: "beginner",
    origin: "Navy SEAL training",
    storyHook: "Used by Navy SEALs to stay calm under extreme pressure—regain control in seconds.",
    usedBy: "Special Forces, Elite Athletes, Emergency Responders",
    thumbnail: "/lovable-uploads/76cee14b-c6a7-4d75-8162-8a5ba6f74a9d.png",
    audioSrc: "/soundscapes/box-breathing.mp3",
    creator: "Navy SEAL training protocol",
    voice: "male",
    language: "en",
    tags: ['water', 'stress-relief', 'performance', 'tactical', 'calm'],
    steps: 5
  },
  {
    id: "bhramari-pranayama",
    title: "Instant Reset Through Bhramari Pranayama (Bee Breath)",
    contentType: "guided-practice",
    category: "pause",
    duration: 4,
    difficulty: "beginner",
    origin: "Ancient yogic calming breath",
    storyHook: "Ancient yogic 'humming bee' breath—instant nervous system reset.",
    usedBy: "Yogis, Meditators, Anxiety Relief",
    thumbnail: "/lovable-uploads/909c474b-063c-47f3-aae1-2ef5c7098a8e.png",
    audioSrc: "/soundscapes/bhramari-pranayama.mp3",
    creator: "Ancient Yogic Calming Breath",
    voice: "female",
    language: "en",
    tags: ['water', 'anxiety-relief', 'gentle', 'calm', 'breathwork'],
    steps: 5
  },
  {
    id: "vagus-wind-down",
    title: "The Vagus Wind-Down",
    contentType: "guided-practice",
    category: "pause",
    duration: 5,
    creator: "Taoist monks and elite combat athletes",
    origin: "Ancient tuning meets modern neuroscience",
    storyHook: "Calm the throat, settle the breath, and signal your nervous system to rest — as taught by Taoist monks and elite combat athletes.",
    voice: "female",
    language: "en",
    thumbnail: "/lovable-uploads/b8ffb35c-7a57-47ef-a879-1aff9c47603d.png",
    audioSrc: "/soundscapes/vagus-wind-down.mp3",
    tags: ['water', 'evening', 'gentle', 'nervous-system', 'sleep-prep', 'calm'],
    steps: 6
  },
  {
    id: "trataka-single-focus",
    title: "Unlock Flow with Trataka (Candle Gazing)",
    contentType: "guided-practice",
    category: "presence",
    duration: 9,
    difficulty: "intermediate",
    origin: "Ancient yogic concentration practice",
    storyHook: "Ancient yogic candle-gazing technique—develop razor-sharp focus and enter flow states at will.",
    usedBy: "Yogis, Deep Work Practitioners, Flow State Seekers",
    thumbnail: "/lovable-uploads/ae4d66fb-b3ea-4ef5-bfff-f228c447224c.png",
    audioSrc: "/soundscapes/trataka-single-focus.mp3",
    creator: "Ancient Yogic Concentration Practice",
    voice: "male",
    language: "en",
    tags: ['air', 'focus', 'advanced', 'flow-state', 'concentration'],
    steps: 6
  },
  {
    id: "energy-forge",
    title: "Energy Through The Forge",
    contentType: "guided-practice",
    category: "power-up",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Physiological state-shifting techniques",
    origin: "Techniques from athletes, performers and Special Forces",
    storyHook: "Rapid activation when energy runs low—when rest isn't an option but energy is required now.",
    voice: "male",
    language: "en",
    thumbnail: "/lovable-uploads/6ad3487d-07e9-414e-96cd-7a73d8a12c03.png",
    audioSrc: "/soundscapes/energy-forge.mp3",
    tags: ['energy', 'activation', 'somatic', 'movement', 'state-shift'],
    steps: 3
  },
  {
    id: "himalayan-monastery",
    title: "Himalayan Monastery — Sacred Chants for Deep Meditation",
    contentType: "guided-practice",
    category: "pause",
    duration: 8,
    difficulty: "beginner",
    creator: "Tibetan Buddhist monastery traditions",
    origin: "High Himalayan meditation practices",
    storyHook: "Experience the profound stillness of Himalayan monks through sacred chants and bells.",
    voice: "none",
    language: "en",
    thumbnail: "/lovable-uploads/cc7c715b-a0d1-4464-b0e1-d338c14452a0.png",
    audioSrc: "/soundscapes/himalayan-monastery.wav",
    tags: ['meditation', 'sacred', 'spiritual', 'deep-calm'],
    steps: 4
  },
  
  // ============= MICRO PRACTICES =============
  
  // PAUSE Micro Practices
  {
    id: "grounding-touch",
    title: "Instant Calm Through Somatic Touch",
    contentType: "micro-practice",
    category: "pause",
    duration: 2,
    difficulty: "beginner",
    creator: "Thomas Hanna, founder of Somatics",
    origin: "Somatic awareness and polyvagal theory",
    storyHook: "For moments of anxiety, overwhelm, panic, emotional flooding, or after receiving hard news",
    thumbnail: "/lovable-uploads/6ad3487d-07e9-414e-96cd-7a73d8a12c03.png",
    tags: ['earth', 'anxiety-relief', 'gentle', 'nervous-system'],
    steps: 4,
    subType: "tool",
    essence: "The body can calm the mind faster than thoughts can. When you touch with awareness, you signal safety directly to your nervous system.",
    cue: "\"Touch. Feel. Soften.\"",
    instructions: [
      "Notice the body alarm (3 seconds): You feel the rush: heart pounding, throat tight, chest heavy. Name it: \"My body is on alert.\"",
      "Make contact — the anchor touch (5 seconds): Choose one: Hand on heart, hand on belly, or both hands on thighs.",
      "The settling breath (10 seconds): Inhale for 4, hold for 2, exhale for 6. Say: \"It's safe to soften.\"",
      "Soothing through micro-movement: Notice what your body wants next—maybe a sigh, a yawn, a shoulder drop. Let it happen."
    ],
    whyThisWorks: "Your skin is a direct access point to your autonomic nervous system. Gentle touch releases oxytocin, lowers cortisol, and activates the vagal brake—a physiological safety signal."
  },
  {
    id: "fudoshin-immovable-mind",
    title: "Calm in Chaos Through Fudōshin",
    contentType: "micro-practice",
    category: "pause",
    duration: 1,
    difficulty: "beginner",
    creator: "Samurai warrior philosophy",
    origin: "Fudōshin (不動心) — The Immovable Mind principle",
    storyHook: "For critical performances, leadership under crisis, public speaking, and confrontation",
    thumbnail: "/lovable-uploads/909c474b-063c-47f3-aae1-2ef5c7098a8e.png",
    tags: ['earth', 'high-pressure', 'leadership', 'performance', 'composure'],
    steps: 4,
    subType: "tool",
    essence: "Your center remains still even when the world around you moves violently. Calm presence in chaos.",
    cue: "\"Still center, moving world.\"",
    instructions: [
      "Root yourself physically (10 seconds): Feet shoulder-width apart. Feel weight drop through your heels.",
      "Find your gravity center (5 seconds): Place hand two inches below navel. Breathe into that spot.",
      "The mountain meditation (15 seconds): Visualize yourself as a mountain—storms pass but you don't flinch.",
      "Micro-adjustments during action: Every 2-3 minutes check: Am I breathing? Is my jaw relaxed?"
    ]
  },
  {
    id: "eye-of-storm",
    title: "Clarity in Chaos Through The Eye",
    contentType: "micro-practice",
    category: "pause",
    duration: 1,
    difficulty: "beginner",
    creator: "Inspired from Sun Tzu",
    origin: "\"In the midst of chaos, there is also opportunity.\" — Sun Tzu",
    storyHook: "For overwhelming situations, information overload, when multiple demands hit simultaneously",
    thumbnail: "/lovable-uploads/cc7c715b-a0d1-4464-b0e1-d338c14452a0.png",
    tags: ['earth', 'overwhelm', 'information-overload', 'focus', 'mastery'],
    steps: 3,
    subType: "tool",
    instructions: [
      "Name the storm (10 seconds): \"I'm in overwhelm. Too many inputs. I need the eye.\"",
      "The single anchor question (20 seconds): Ask: \"What is the ONE thing that, if handled now, makes everything else easier?\"",
      "Act from the center (ongoing): Do that one thing. Ignore everything else until it's done."
    ]
  },
  
  // POWER-UP Micro Practices
  {
    id: "phoenix-mindset",
    title: "Momentum Through Phoenix Rising",
    contentType: "micro-practice",
    category: "power-up",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Ancient mythology meets modern psychology",
    origin: "Phoenix rising from ashes metaphor",
    storyHook: "Turn setbacks into comebacks—rise stronger from every failure",
    thumbnail: "/lovable-uploads/b8ffb35c-7a57-47ef-a879-1aff9c47603d.png",
    tags: ['resilience', 'recovery', 'transformation', 'growth'],
    steps: 3,
    subType: "mindset",
    instructions: [
      "Name the ashes: Acknowledge what broke. \"This failed. I'm in the ashes.\"",
      "Find the ember: Ask: \"What did I learn? What's still alive in me?\"",
      "Rise with it: Take one action that proves you're not done. Start small."
    ]
  },
  {
    id: "ikigai-purpose",
    title: "Meaning Through Ikigai",
    contentType: "micro-practice",
    category: "power-up",
    duration: 2,
    difficulty: "beginner",
    creator: "Japanese philosophy",
    origin: "Japanese concept of life purpose",
    storyHook: "Connect daily tasks to deeper purpose—fuel intrinsic motivation",
    thumbnail: "/lovable-uploads/ae4d66fb-b3ea-4ef5-bfff-f228c447224c.png",
    tags: ['purpose', 'meaning', 'motivation', 'fulfillment'],
    steps: 4,
    subType: "mindset",
    instructions: [
      "Name the task: What feels meaningless right now?",
      "Find the thread: How does this connect to what matters to you?",
      "Reframe with purpose: \"I'm not just [doing task]. I'm [higher purpose].\"",
      "Hold that frame: Before starting, repeat the purpose frame once."
    ]
  },
  {
    id: "buddhist-phoenix",
    title: "Resilience Through the Buddhist Phoenix",
    contentType: "micro-practice",
    category: "power-up",
    duration: 2,
    difficulty: "intermediate",
    creator: "Buddhist teaching",
    origin: "\"No mud, no lotus.\" — Thích Nhất Hạnh",
    storyHook: "Beauty emerges from suffering—the lotus grows in muddy water",
    thumbnail: "/lovable-uploads/76cee14b-c6a7-4d75-8162-8a5ba6f74a9d.png",
    tags: ['resilience', 'recovery', 'hardship', 'growth'],
    steps: 4,
    subType: "mindset",
    instructions: [
      "Name the mud: \"I'm in the mud right now. This is where growth happens.\"",
      "Micro-signs of growth: Look for tiny improvements daily.",
      "Reframe suffering as composting: The mud is fuel for wisdom and strength.",
      "Honor the mud: When you emerge, remember you grew because of it."
    ]
  },
  {
    id: "energy-through-reframe",
    title: "Energy Through Reframe",
    contentType: "micro-practice",
    category: "power-up",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Cognitive reappraisal techniques",
    origin: "Psychology and neuroscience",
    storyHook: "Rapid activation when energy runs low through mental reframing",
    thumbnail: "/lovable-uploads/909c474b-063c-47f3-aae1-2ef5c7098a8e.png",
    tags: ['energy', 'reframe', 'motivation', 'fatigue'],
    steps: 3,
    subType: "mindset"
  },
  {
    id: "courage-future-self",
    title: "Courage Through The Future Self",
    contentType: "micro-practice",
    category: "power-up",
    duration: 3,
    difficulty: "beginner",
    creator: "Stoic philosophy meets modern psychology",
    origin: "Regret Minimization Framework",
    storyHook: "Act with courage by consulting your future self",
    thumbnail: "/lovable-uploads/cc7c715b-a0d1-4464-b0e1-d338c14452a0.png",
    tags: ['courage', 'fear', 'decision', 'growth'],
    steps: 5,
    subType: "mindset"
  },
  {
    id: "confidence-through-evidence",
    title: "Confidence Through Evidence",
    contentType: "micro-practice",
    category: "power-up",
    duration: 2,
    difficulty: "beginner",
    creator: "Cognitive Behavioral Therapy",
    origin: "CBT and sports psychology",
    storyHook: "Rebuild self-belief with your own proof",
    thumbnail: "/lovable-uploads/06444f60-b3bd-4d38-a749-aea185d789e6.png",
    tags: ['confidence', 'self-belief', 'performance', 'evidence'],
    steps: 3,
    subType: "mindset"
  },
  
  // PRESENCE Micro Practices
  {
    id: "single-thread-focus",
    title: "Entry Through The Single Thread",
    contentType: "micro-practice",
    category: "presence",
    duration: 2,
    difficulty: "beginner",
    creator: "Zen meditation meets deep work",
    origin: "Zen single-pointed concentration",
    storyHook: "Lock attention by choosing one anchor",
    thumbnail: "/lovable-uploads/7a5dd5f2-96fb-485c-a58f-0280491740c1.png",
    tags: ['focus', 'attention', 'deep-work', 'concentration'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "first-move-momentum",
    title: "Momentum Through The First Move",
    contentType: "micro-practice",
    category: "presence",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Physics meets habit formation",
    origin: "Newton's First Law applied to action",
    storyHook: "Overcome inertia with the smallest possible start",
    thumbnail: "/lovable-uploads/afddfc0a-07c8-4659-bfb5-560d510b12c3.png",
    tags: ['procrastination', 'inertia', 'starting', 'momentum'],
    steps: 3,
    subType: "mindset"
  },
  {
    id: "depth-subtraction",
    title: "Depth Through Subtraction",
    contentType: "micro-practice",
    category: "presence",
    duration: 2,
    difficulty: "beginner",
    creator: "Essentialism philosophy",
    origin: "Michelangelo's sculpture metaphor",
    storyHook: "Achieve clarity by removing, not adding",
    thumbnail: "/lovable-uploads/4ed33e6d-77b9-47f9-9981-bab218507307.png",
    tags: ['essentialism', 'priorities', 'subtraction', 'clarity'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "eternal-now-presence",
    title: "Presence Through The Eternal Now",
    contentType: "micro-practice",
    category: "presence",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Buddhist mindfulness",
    origin: "The Power of Now philosophy",
    storyHook: "Anchor in this moment, the only one that exists",
    thumbnail: "/lovable-uploads/aa4d150b-e5fe-48d7-aa74-9f082d21ffaa.png",
    tags: ['mindfulness', 'present-moment', 'awareness', 'attention'],
    steps: 3,
    subType: "mindset"
  },
  {
    id: "rhythm-pulse",
    title: "Rhythm Through The Pulse",
    contentType: "micro-practice",
    category: "presence",
    duration: 2,
    difficulty: "beginner",
    creator: "Ultradian rhythms research",
    origin: "Biological performance cycles",
    storyHook: "Sustain performance through strategic oscillation",
    thumbnail: "/lovable-uploads/6ad3487d-07e9-414e-96cd-7a73d8a12c03.png",
    tags: ['recovery', 'ultradian-rhythm', 'breaks', 'sustainability'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "mastery-constraint",
    title: "Mastery Through Constraint",
    contentType: "micro-practice",
    category: "presence",
    duration: 2.5,
    difficulty: "intermediate",
    creator: "Deliberate practice research",
    origin: "Theory of Constraints applied to skill",
    storyHook: "Accelerate learning by limiting options",
    thumbnail: "/lovable-uploads/909c474b-063c-47f3-aae1-2ef5c7098a8e.png",
    tags: ['deliberate-practice', 'skill-building', 'constraint', 'mastery'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "wu-wei-flow",
    title: "Effortless Action Through Wu Wei",
    contentType: "micro-practice",
    category: "presence",
    duration: 2,
    difficulty: "intermediate",
    creator: "Taoist philosophy",
    origin: "Ancient Chinese philosophy of effortless action",
    storyHook: "Move with the flow, not against it—achieve more by forcing less",
    thumbnail: "/lovable-uploads/76cee14b-c6a7-4d75-8162-8a5ba6f74a9d.png",
    tags: ['flow', 'taoism', 'effortless', 'alignment'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "mushin-flow",
    title: "Flow Through Mushin (No-Mind)",
    contentType: "micro-practice",
    category: "presence",
    duration: 2,
    difficulty: "advanced",
    creator: "Zen martial arts",
    origin: "Japanese swordsmanship philosophy",
    storyHook: "Enter the state of no-mind where action flows without thought",
    thumbnail: "/lovable-uploads/cc7c715b-a0d1-4464-b0e1-d338c14452a0.png",
    tags: ['flow', 'zen', 'mastery', 'intuition'],
    steps: 4,
    subType: "mindset"
  },
  {
    id: "jobs-simplicity",
    title: "Clarity Through Simplicity",
    contentType: "micro-practice",
    category: "presence",
    duration: 1.5,
    difficulty: "beginner",
    creator: "Steve Jobs philosophy",
    origin: "Apple design principles",
    storyHook: "Simplicity is the ultimate sophistication—cut to what matters",
    thumbnail: "/lovable-uploads/ae4d66fb-b3ea-4ef5-bfff-f228c447224c.png",
    tags: ['simplicity', 'clarity', 'essentialism', 'focus'],
    steps: 3,
    subType: "mindset"
  },
  {
    id: "stoic-reflection",
    title: "Stoic Evening Reflection",
    contentType: "micro-practice",
    category: "presence",
    duration: 10,
    difficulty: "beginner",
    creator: "Stoic Philosophy",
    origin: "Marcus Aurelius daily practice",
    storyHook: "The Roman Emperor's practice of reviewing actions and alignment at day's end",
    thumbnail: "/lovable-uploads/06444f60-b3bd-4d38-a749-aea185d789e6.png",
    tags: ['air', 'evening-ritual', 'gentle', 'clarity'],
    steps: 5,
    subType: "mindset"
  }
];
