import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { DEV_MODE, DEV_USER } from '@/config/devMode';
import { getAuthToken } from '@/services/authTokenService';

interface Activity {
  id: string;
  type: 'assessment' | 'recalibrate' | 'brief';
  title: string;
  date: Date;
  sessionId?: string;
  briefId?: string;
}

const getAccessTokenOrAnon = async () => {
  if (DEV_MODE) {
    return import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
  }
  return await getAuthToken();
};

const capitalize = (s: string) => s ? s.charAt(0).toUpperCase() + s.slice(1).toLowerCase() : '';

const levelIcon = (level: number | null | undefined): string => {
  if (level == null) return '';
  if (level >= 4) return '▲';
  if (level <= 2) return '▼';
  return '●';
};

export const useRecentActivity = ({ enabled = true }: { enabled?: boolean } = {}) => {
  const { user } = useAuth();

  const { data: activities = [], isLoading } = useQuery({
    queryKey: ['recent-activity', user?.id],
    queryFn: async (): Promise<Activity[]> => {
      if (!user?.id) return [];

      const allActivities: Activity[] = [];
      const accessToken = await getAccessTokenOrAnon();
      if (!accessToken) return [];

      // Fetch recent assessments (MRS v3, 4 dimensions).
      // Fixed order: Clarity, Emotion, Pressure, Regulation so the eye learns
      // the position. One short positive-direction word per dim — the arrow
      // carries the level (▲ high / ● mid / ▼ low). Keeps the row within the
      // sidebar width without changing markup.
      try {
        const { data, error } = await supabase.functions.invoke('daily-checkins', {
          headers: { Authorization: `Bearer ${accessToken}` },
          body: { action: 'GET_RECENT_CHECKINS', limit: 10 },
        });
        if (!error && data?.data) {
          data.data.forEach((checkin: any) => {
            const dims: Array<[number | null | undefined, string]> = [
              [checkin.clarity_level, 'Clear'],
              [checkin.emotion_level, 'Steady'],
              [checkin.pressure_level, 'Ease'],
              [checkin.regulation_level, 'Poised'],
            ];
            const parts = dims
              .map(([lvl, word]) => {
                const icon = levelIcon(lvl);
                return icon ? `${icon} ${word}` : '';
              })
              .filter(Boolean);
            const title = parts.length ? parts.join(', ') : 'Assessment';

            allActivities.push({
              id: checkin.id,
              type: 'assessment',
              title,
              date: new Date(checkin.created_at ?? checkin.checkin_date),
            });
          });
        }
      } catch (err) {
        console.error('[useRecentActivity] Failed to fetch assessments:', err);
      }

      // Fetch recent sanctuary/reset events
      try {
        const { data, error } = await supabase.functions.invoke('user-events', {
          headers: { Authorization: `Bearer ${accessToken}` },
          body: { action: 'GET_RECENT_SANCTUARY_EVENTS', limit: 5 },
        });
        if (!error && data?.success && data.data) {
          data.data.forEach((event: any) => {
            allActivities.push({
              id: event.id,
              type: 'recalibrate',
              title: capitalize(event.content_type || event.category || 'Reset'),
              date: new Date(event.timestamp),
            });
          });
        }
      } catch (err) {
        console.error('[useRecentActivity] Failed to fetch sanctuary events:', err);
      }

      // Fetch recent Past Briefs from the canonical brief_snapshots store.
      // Sourcing from snapshots (not brief_view engagement events) guarantees
      // the sidebar only shows briefs that were actually generated by the
      // MRS gate in compute-inner/outer-readiness. If no snapshot exists
      // (e.g. wearable missing), no Past Brief row appears.
      try {
        const { data, error } = await supabase.functions.invoke('brief-history', {
          method: 'GET',
          headers: { Authorization: `Bearer ${accessToken}` },
        });
        if (!error && Array.isArray(data?.briefs)) {
          data.briefs.slice(0, 5).forEach((snap: any) => {
            const phrase: string =
              snap.refined_phrase || snap.phrase || snap.baseline_phrase || 'Brief';
            allActivities.push({
              id: snap.id,
              type: 'brief',
              title: phrase.length > 30 ? phrase.slice(0, 30) + '…' : phrase,
              date: new Date(snap.created_at),
              briefId: snap.id,
            });
          });
        }
      } catch (err) {
        console.error('[useRecentActivity] Failed to fetch brief snapshots:', err);
      }

      // Sort all activities by date and return top 10
      return allActivities
        .sort((a, b) => b.date.getTime() - a.date.getTime())
        .slice(0, 15);
    },
    enabled: enabled && !!user?.id,
    staleTime: 1000 * 60 * 5,
  });

  return { activities, isLoading };
};
