import jsPDF from 'jspdf';

interface DebriefData {
  scenarioDomain?: string;
  contextType?: string;
  scenarioContext?: string;
  sessionDuration?: string;
  mentalFitnessScore?: number;
  mentalFitnessChange?: number;
  strengths?: string[];
  blindSpots?: string[];
  mentalModels?: string[];
  personalNotes?: string;
  date?: Date;
}

export const generateDebriefPdf = (data: DebriefData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;
  
  // Helper function to add text with word wrap
  const addWrappedText = (text: string, x: number, y: number, maxWidth: number, lineHeight: number = 7): number => {
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * lineHeight);
  };
  
  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Dialogue Debrief', margin, yPos);
  yPos += 10;
  
  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  const dateStr = (data.date || new Date()).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(dateStr, margin, yPos);
  yPos += 15;
  
  // Session Context Section
  doc.setTextColor(0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Session Context', margin, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  if (data.scenarioDomain) {
    doc.text(`Category: ${data.scenarioDomain}`, margin, yPos);
    yPos += 6;
  }
  if (data.contextType) {
    doc.text(`Scenario: ${data.contextType}`, margin, yPos);
    yPos += 6;
  }
  if (data.sessionDuration) {
    doc.text(`Duration: ${data.sessionDuration}`, margin, yPos);
    yPos += 6;
  }
  yPos += 8;
  
  // Mental Fitness Score
  if (data.mentalFitnessScore) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Mental Fitness Score', margin, yPos);
    yPos += 8;
    
    doc.setFontSize(24);
    doc.setTextColor(74, 85, 104);
    doc.text(`${data.mentalFitnessScore}`, margin, yPos);
    
    if (data.mentalFitnessChange) {
      doc.setFontSize(12);
      doc.setTextColor(34, 139, 34);
      doc.text(`+${data.mentalFitnessChange} from baseline`, margin + 30, yPos);
    }
    yPos += 15;
  }
  
  // Strengths Section
  if (data.strengths && data.strengths.length > 0) {
    doc.setTextColor(0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Strengths', margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.strengths.forEach((strength) => {
      doc.text(`• ${strength}`, margin + 4, yPos);
      yPos += 6;
    });
    yPos += 8;
  }
  
  // Blind Spots Section
  if (data.blindSpots && data.blindSpots.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Blind Spots Revealed', margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.blindSpots.forEach((blindSpot) => {
      doc.text(`• ${blindSpot}`, margin + 4, yPos);
      yPos += 6;
    });
    yPos += 8;
  }
  
  // Mental Models Section
  if (data.mentalModels && data.mentalModels.length > 0) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Mental Models Applied', margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    data.mentalModels.forEach((model) => {
      doc.text(`• ${model}`, margin + 4, yPos);
      yPos += 6;
    });
    yPos += 8;
  }
  
  // Personal Notes Section
  if (data.personalNotes) {
    // Check if we need a new page
    if (yPos > 240) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Personal Reflection', margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    yPos = addWrappedText(data.personalNotes, margin, yPos, pageWidth - (margin * 2));
    yPos += 8;
  }
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Mind Module - Dialogue Room', margin, footerY);
  doc.text('mindmodule.app', pageWidth - margin - 30, footerY);
  
  // Save the PDF
  const filename = `dialogue-debrief-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};
