-- Add encrypted address columns to certificate_requests
ALTER TABLE public.certificate_requests
  ADD COLUMN IF NOT EXISTS address_blob_enc text,
  ADD COLUMN IF NOT EXISTS address_iv text,
  ADD COLUMN IF NOT EXISTS address_enc_v int DEFAULT 1;

-- Create audit_logs table (service-role write only, no browser reads)
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  actor text,                      -- Auth0 sub or "system"
  action text NOT NULL,            -- CERT_REQUEST_CREATE / CERT_REQUEST_VIEW etc.
  table_name text,
  record_id text,
  metadata jsonb
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs FORCE ROW LEVEL SECURITY;

-- Only service role can insert (edge functions)
CREATE POLICY "Service role can insert audit logs"
ON public.audit_logs FOR INSERT
WITH CHECK (auth.role() = 'service_role');

-- Force RLS on sensitive tables
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE public.certificate_requests FORCE ROW LEVEL SECURITY;