INSERT INTO public.sanctuary_content (id, title, content_type, category, duration, difficulty, creator, origin, story_hook, used_by, sub_type, language, thumbnail_url, steps_count, tags, is_active, display_order, protocol_type, intensity_level, energy_direction, goal_tags, physio_targets, equipment, environment) VALUES
('difficult-conversation-prep','Prepare for a High-Stakes Conversation','micro-practice','pause',3,'beginner','Sun Tzu + Stoic Philosophy + FBI Behavioral Analysis Unit','The Art of War + Marcus Aurelius Meditations + FBI Negotiation Protocol','Before every battle Sun Tzu said: know yourself first. Before every high-stakes conversation, the most dangerous thing is walking in emotionally activated.','CEOs, C-Suite Leaders, Diplomats, Crisis Negotiators','mindset','en','/assets/recalibrate/pause/difficult-conversation-prep.jpg',4,ARRAY['difficult-conversation','composure','preparation','high-stakes'],true,0,'mindset','low','stabilize',ARRAY['composure','emotional_regulation','clarity','performance'],ARRAY['cortisol_reduce','prefrontal_activation'],ARRAY['none'],ARRAY['private','office','home']),
('deep-work-initiation','Deep Work Initiation','micro-practice','presence',3,'beginner','Cal Newport + Zen Philosophy + William James','Deep Work (Newport) + Zen beginner''s mind + The Principles of Psychology (James)','William James called attention the rarest and purest exertion of will. Leaders who access 3-4 hours of genuine deep work produce more strategic value than those working 12 hours at surface level.','CEOs, Executives, Founders entering deep strategic, creative or analytical work','mindset','en','/assets/recalibrate/presence/deep-work-initiation.jpg',4,ARRAY['deep-work','focus','flow','productivity','concentration'],true,0,'mindset','low','clarify',ARRAY['focus','mental_clarity','sustained_attention','flow'],ARRAY['prefrontal_activation','focus_enhancement'],ARRAY['none'],ARRAY['private','office','home']),
('rapid-recharge-midday','Rapid Midday Recharge','micro-practice','power-up',5,'beginner','NASA Sleep Research + Winston Churchill + Aristotle Onassis','NASA study on napping + Churchill''s wartime recovery rituals + Mediterranean power rest tradition','Churchill ran a war partly on naps. NASA research confirmed a 26-minute rest improved pilot performance by 34%. The most effective executives recovered from depletion strategically.','CEOs and C-Suite Leaders experiencing genuine midday cognitive depletion','mindset','en','/assets/recalibrate/power-up/rapid-recharge-midday.jpg',4,ARRAY['recovery','recharge','rest','energy','performance'],true,0,'mindset','low','downshift',ARRAY['energy','mental_clarity','focus','performance'],ARRAY['parasympathetic_activation','hrv_increase','cortisol_reduce'],ARRAY['none'],ARRAY['private','office','home']);

INSERT INTO public.sanctuary_content_metadata (id, content_id, structured_tags, completion_quote, intro_summary, essence, parallel, cue, why_this_works, mastery_category, horizon, meta_skill, is_foundational, moment, state_signal, duration_band) VALUES
(gen_random_uuid(),'difficult-conversation-prep','{"pillar":"pause","intensityLevel":"low","energyDirection":"stabilize","contextTags":["high_stakes_conversation","board_confrontation","difficult_feedback","conflict"],"goalTags":["composure","emotional_regulation","clarity","performance"],"physioTarget":["cortisol_reduce","prefrontal_activation"],"equipment":["none"],"environmentSuitability":["office","home","private"],"socialTag":"solo"}','The conversation is yours to lead. You walked in ready.','Before a difficult conversation. Activate tactical calm, not emotional reaction.','You cannot negotiate from inside the fire. Step outside it first.','Tactical empathy (FBI); Stoic preparation (Meditations VIII); Sun Tzu self-knowledge before battle','I see clearly. I''m anchored. I''m ready.','When emotionally activated, the prefrontal cortex goes offline. This protocol lowers cortisol and activates the Observer Self before you enter, so you respond rather than react.','{"primary":"meta-clarity","secondary":["pause"]}','{immediate}','{meta-clarity}',false,'{moment-pre-jit,moment-crisis}','{signal-tense,signal-clarity-low}','micro'),
(gen_random_uuid(),'deep-work-initiation','{"pillar":"flow","intensityLevel":"low","energyDirection":"clarify","contextTags":["deep_work","strategy_work","writing","complex_analysis"],"goalTags":["focus","mental_clarity","sustained_attention","flow"],"physioTarget":["prefrontal_activation","focus_enhancement"],"equipment":["none"],"environmentSuitability":["office","home","private"],"socialTag":"solo"}','You entered the deep. The work will meet you there.','Before strategic thinking, writing, or complex analysis. Enter the state where real work happens.','Deep work is not longer work. It''s different work. Enter it deliberately.','Flow state induction (Csikszentmihalyi); Attention training (James); Ultradian rhythm; Monk mode (Newport)','For this time, I am only here. Everything else waits.','The brain does not enter deep work automatically under modern conditions. This protocol suppresses the default mode network and activates the task-positive network associated with focused performance.','{"primary":"meta-clarity","secondary":["presence"]}','{immediate}','{meta-clarity}',false,'{moment-pre-jit}','{signal-clarity-low,signal-overloaded}','micro'),
(gen_random_uuid(),'rapid-recharge-midday','{"pillar":"renewal","intensityLevel":"low","energyDirection":"downshift","contextTags":["energy_crash","diminishing_returns","cognitive_fatigue","long_session"],"goalTags":["energy","mental_clarity","focus","performance"],"physioTarget":["parasympathetic_activation","hrv_increase","cortisol_reduce"],"equipment":["none"],"environmentSuitability":["office","home","private"],"socialTag":"solo"}','You did not lose 15 minutes. You gained the next 3 hours.','Cognitively depleted mid-day. Strategic rest is not weakness, it is performance engineering.','Strategic rest is not laziness. It''s performance engineering.','Ultradian rhythm (90-minute cycles); Stage N1 nap benefits; napping research (Mednick)','Rest is preparation. I am refueling.','The brain accumulates adenosine through the day, degrading cognitive performance. A brief eyes-closed rest clears adenosine and restores prefrontal function.','{"primary":"meta-energy","secondary":["power-up"]}','{immediate}','{meta-energy}',false,'{moment-pre-jit}','{signal-depleted,signal-clarity-low}','micro');

INSERT INTO public.sanctuary_content_steps (id, content_id, step_order, title, instruction, duration, breathing_pattern, wisdom_note) VALUES
(gen_random_uuid(),'difficult-conversation-prep',1,'Name the Threat','In your mind or on paper, complete this sentence: I am walking into this conversation feeling ___. Name it precisely: nervous, afraid of their reaction, guilty, angry. Do not judge it. Just name it. FBI negotiators call this labeling.',60,NULL,'Name it and it loses power over you. The unnamed is what controls you.'),
(gen_random_uuid(),'difficult-conversation-prep',2,'Separate Person from Position','Ask yourself: what do THEY need from this conversation? Not what you think they should accept, but what they actually need to feel heard and fairly treated. Write two things.',60,NULL,'Marcus Aurelius prepared for every difficult day by imagining the minds of others. Empathy is not weakness, it is intelligence.'),
(gen_random_uuid(),'difficult-conversation-prep',3,'Choose Your One Intention','What is the ONE outcome that would make this conversation a success? Not winning, not being right. Write it in one sentence. This becomes your anchor if the conversation goes sideways.',45,NULL,'A great negotiator knows their walk-away position before sitting down. Know yours.'),
(gen_random_uuid(),'difficult-conversation-prep',4,'Ground and Regulate','Three slow breaths: 4 counts in, 6 counts out. Feel your feet on the floor. Say internally: I am safe. I am prepared. I can handle whatever comes.',45,'4 in, 6 out x3','Composure is not the absence of feeling. It is feeling everything and choosing your response.'),
(gen_random_uuid(),'deep-work-initiation',1,'Clear the Environment','Phone away, not just silent, away. One window open. One task visible. Nothing else. Every visible distraction reduces cognitive bandwidth even if you are not using it.',45,NULL,'Your physical environment is your mental environment. Architect it intentionally.'),
(gen_random_uuid(),'deep-work-initiation',2,'State Your Single Objective','Write in one sentence: In this session I am doing only ___. Not a list. One thing. The brain enters deep work through a single doorway.',30,NULL,'The mind narrows to go deep. Width is the enemy of depth.'),
(gen_random_uuid(),'deep-work-initiation',3,'The Entry Breath','Close your eyes. Three slow breaths. With each exhale, imagine releasing the previous 24 hours. With your final inhale, arrive only here. This moment. This task.',45,'4 in, 6 out x3','The warrior entering battle is not thinking about yesterday''s battle.'),
(gen_random_uuid(),'deep-work-initiation',4,'Start the Work','The first five minutes are the hardest. Begin without judgment. The act of starting activates the reward system, which makes continuation progressively easier.',30,NULL,'You cannot think your way into deep work. You work your way into deep thought.'),
(gen_random_uuid(),'rapid-recharge-midday',1,'Create the Conditions','Close your door or find a quiet space. Phone away. Set an alarm for 15 minutes. Recline or sit back. Lower the lights if possible.',60,NULL,'The environment for rest is itself a leadership choice. Design it deliberately.'),
(gen_random_uuid(),'rapid-recharge-midday',2,'Release the Day','Eyes closed. Three slow deliberate exhales, releasing the morning''s decisions and conversations. They will be there when you return. For the next twelve minutes, your only job is to not have a job.',60,'4 in, long out x3','The most productive thing you can do right now is stop being productive.'),
(gen_random_uuid(),'rapid-recharge-midday',3,'Rest or Sleep','You may fall into light sleep, or simply rest with eyes closed. Both deliver benefit. Do not force sleep. Simply allow your mind to drift. The body knows what it needs.',540,NULL,'Nature has not intended man to work from eight in the morning to midnight without refreshment.'),
(gen_random_uuid(),'rapid-recharge-midday',4,'Return Deliberately','When the alarm sounds, do not spring up. Take one minute. Breathe deliberately. Drink water. Notice the shift in cognitive clarity. Write one thought about what you are returning to, then return fully.',60,NULL,'You are now functioning on a cleared system.');