-- Add text overload for has_role to support Auth0 string user IDs
CREATE OR REPLACE FUNCTION public.has_role(_user_id text, _role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  );
$$;

GRANT EXECUTE ON FUNCTION public.has_role(text, public.app_role) TO authenticated, service_role;

DROP POLICY IF EXISTS "Admins can delete content" ON public.sanctuary_content;
CREATE POLICY "Admins can delete content" ON public.sanctuary_content FOR DELETE USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Admins can insert content" ON public.sanctuary_content;
CREATE POLICY "Admins can insert content" ON public.sanctuary_content FOR INSERT WITH CHECK (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Admins can update content" ON public.sanctuary_content;
CREATE POLICY "Admins can update content" ON public.sanctuary_content FOR UPDATE USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role)) WITH CHECK (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify usage occasions" ON public.usage_occasion_definitions;
CREATE POLICY "Only admins can modify usage occasions" ON public.usage_occasion_definitions FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can assign roles" ON public.user_roles;
CREATE POLICY "Only admins can assign roles" ON public.user_roles FOR INSERT WITH CHECK (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can delete roles" ON public.user_roles;
CREATE POLICY "Only admins can delete roles" ON public.user_roles FOR DELETE USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify checkin tags" ON public.checkin_tag_definitions;
CREATE POLICY "Only admins can modify checkin tags" ON public.checkin_tag_definitions FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify meta skills" ON public.meta_skill_definitions;
CREATE POLICY "Only admins can modify meta skills" ON public.meta_skill_definitions FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify metadata" ON public.sanctuary_content_metadata;
CREATE POLICY "Only admins can modify metadata" ON public.sanctuary_content_metadata FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify soft skills" ON public.soft_skill_definitions;
CREATE POLICY "Only admins can modify soft skills" ON public.soft_skill_definitions FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify steps" ON public.sanctuary_content_steps;
CREATE POLICY "Only admins can modify steps" ON public.sanctuary_content_steps FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can modify sub skills" ON public.sub_skill_definitions;
CREATE POLICY "Only admins can modify sub skills" ON public.sub_skill_definitions FOR ALL USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Only admins can view roles" ON public.user_roles;
CREATE POLICY "Only admins can view roles" ON public.user_roles FOR SELECT USING (has_role((auth.jwt() ->> 'sub'), 'admin'::app_role));
DROP POLICY IF EXISTS "Users can delete their own favorites" ON public.user_favorites;
CREATE POLICY "Users can delete their own favorites" ON public.user_favorites FOR DELETE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can delete their own ritual completions" ON public.daily_ritual_completions;
CREATE POLICY "Users can delete their own ritual completions" ON public.daily_ritual_completions FOR DELETE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can delete their own saved debriefs" ON public.saved_debriefs;
CREATE POLICY "Users can delete their own saved debriefs" ON public.saved_debriefs FOR DELETE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert own intervention outcomes" ON public.coach_intervention_outcomes;
CREATE POLICY "Users can insert own intervention outcomes" ON public.coach_intervention_outcomes FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert own onboarding progress" ON public.onboarding_progress;
CREATE POLICY "Users can insert own onboarding progress" ON public.onboarding_progress FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert own skip events" ON public.checkin_skip_events;
CREATE POLICY "Users can insert own skip events" ON public.checkin_skip_events FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own achievements" ON public.user_achievements;
CREATE POLICY "Users can insert their own achievements" ON public.user_achievements FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own certificate requests" ON public.certificate_requests;
CREATE POLICY "Users can insert their own certificate requests" ON public.certificate_requests FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own checkins" ON public.daily_checkins;
CREATE POLICY "Users can insert their own checkins" ON public.daily_checkins FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own device tokens" ON public.notification_device_tokens;
CREATE POLICY "Users can insert their own device tokens" ON public.notification_device_tokens FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own engagements" ON public.user_engagements;
CREATE POLICY "Users can insert their own engagements" ON public.user_engagements FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own events" ON public.sanctuary_events;
CREATE POLICY "Users can insert their own events" ON public.sanctuary_events FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own favorites" ON public.user_favorites;
CREATE POLICY "Users can insert their own favorites" ON public.user_favorites FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own feedback" ON public.content_relevance_feedback;
CREATE POLICY "Users can insert their own feedback" ON public.content_relevance_feedback FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own fitness scores" ON public.mental_fitness_scores;
CREATE POLICY "Users can insert their own fitness scores" ON public.mental_fitness_scores FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own inner readiness scores" ON public.inner_readiness_scores;
CREATE POLICY "Users can insert their own inner readiness scores" ON public.inner_readiness_scores FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own intervention events" ON public.micro_intervention_events;
CREATE POLICY "Users can insert their own intervention events" ON public.micro_intervention_events FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own meta skill progress" ON public.meta_skill_progress;
CREATE POLICY "Users can insert their own meta skill progress" ON public.meta_skill_progress FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own notification preferences" ON public.notification_preferences;
CREATE POLICY "Users can insert their own notification preferences" ON public.notification_preferences FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can insert their own practice sessions" ON public.practice_sessions FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own preferences" ON public.user_preferences;
CREATE POLICY "Users can insert their own preferences" ON public.user_preferences FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = id));
DROP POLICY IF EXISTS "Users can insert their own ritual completions" ON public.daily_ritual_completions;
CREATE POLICY "Users can insert their own ritual completions" ON public.daily_ritual_completions FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own saved debriefs" ON public.saved_debriefs;
CREATE POLICY "Users can insert their own saved debriefs" ON public.saved_debriefs FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own session feedback" ON public.session_feedback;
CREATE POLICY "Users can insert their own session feedback" ON public.session_feedback FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own snapshots" ON public.energy_snapshots;
CREATE POLICY "Users can insert their own snapshots" ON public.energy_snapshots FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own tiny wins" ON public.tiny_wins;
CREATE POLICY "Users can insert their own tiny wins" ON public.tiny_wins FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert their own wearable data" ON public.wearable_data;
CREATE POLICY "Users can insert their own wearable data" ON public.wearable_data FOR INSERT WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can read own coach insights" ON public.user_coach_insights;
CREATE POLICY "Users can read own coach insights" ON public.user_coach_insights FOR SELECT TO authenticated USING ((user_id = ( SELECT (auth.jwt() ->> 'sub') AS uid)));
DROP POLICY IF EXISTS "Users can read own daily_themes" ON public.daily_themes;
CREATE POLICY "Users can read own daily_themes" ON public.daily_themes FOR SELECT TO authenticated USING ((user_id = ( SELECT (auth.jwt() ->> 'sub') AS uid)));
DROP POLICY IF EXISTS "Users can update their own notification preferences" ON public.notification_preferences;
CREATE POLICY "Users can update their own notification preferences" ON public.notification_preferences FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can update their own practice sessions" ON public.practice_sessions FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can read own integrations" ON public.user_integrations;
CREATE POLICY "Users can read own integrations" ON public.user_integrations FOR SELECT TO authenticated USING ((user_id = ( SELECT (auth.jwt() ->> 'sub') AS uid)));
DROP POLICY IF EXISTS "Users can update own intervention outcomes" ON public.coach_intervention_outcomes;
CREATE POLICY "Users can update own intervention outcomes" ON public.coach_intervention_outcomes FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update own onboarding progress" ON public.onboarding_progress;
CREATE POLICY "Users can update own onboarding progress" ON public.onboarding_progress FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own achievements" ON public.user_achievements;
CREATE POLICY "Users can update their own achievements" ON public.user_achievements FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own fitness scores" ON public.mental_fitness_scores;
CREATE POLICY "Users can update their own fitness scores" ON public.mental_fitness_scores FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own inner readiness scores" ON public.inner_readiness_scores;
CREATE POLICY "Users can update their own inner readiness scores" ON public.inner_readiness_scores FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own meta skill progress" ON public.meta_skill_progress;
CREATE POLICY "Users can update their own meta skill progress" ON public.meta_skill_progress FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own notification logs" ON public.notification_log;
CREATE POLICY "Users can update their own notification logs" ON public.notification_log FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own preferences" ON public.user_preferences;
CREATE POLICY "Users can update their own preferences" ON public.user_preferences FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own profile" ON public.profiles;
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (((auth.jwt() ->> 'sub') = id));
DROP POLICY IF EXISTS "Users can update their own ritual completions" ON public.daily_ritual_completions;
CREATE POLICY "Users can update their own ritual completions" ON public.daily_ritual_completions FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own saved debriefs" ON public.saved_debriefs;
CREATE POLICY "Users can update their own saved debriefs" ON public.saved_debriefs FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own snapshots" ON public.energy_snapshots;
CREATE POLICY "Users can update their own snapshots" ON public.energy_snapshots FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update their own wearable data" ON public.wearable_data;
CREATE POLICY "Users can update their own wearable data" ON public.wearable_data FOR UPDATE USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own carousel cards" ON public.jit_carousel_cards;
CREATE POLICY "Users can view own carousel cards" ON public.jit_carousel_cards FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own intervention outcomes" ON public.coach_intervention_outcomes;
CREATE POLICY "Users can view own intervention outcomes" ON public.coach_intervention_outcomes FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own onboarding progress" ON public.onboarding_progress;
CREATE POLICY "Users can view own onboarding progress" ON public.onboarding_progress FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own pill logs" ON public.jit_pill_display_log;
CREATE POLICY "Users can view own pill logs" ON public.jit_pill_display_log FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own skip events" ON public.checkin_skip_events;
CREATE POLICY "Users can view own skip events" ON public.checkin_skip_events FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own tools" ON public.coach_tools_offered;
CREATE POLICY "Users can view own tools" ON public.coach_tools_offered FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own achievements" ON public.user_achievements;
CREATE POLICY "Users can view their own achievements" ON public.user_achievements FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own certificate requests" ON public.certificate_requests;
CREATE POLICY "Users can view their own certificate requests" ON public.certificate_requests FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own checkins" ON public.daily_checkins;
CREATE POLICY "Users can view their own checkins" ON public.daily_checkins FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own device tokens" ON public.notification_device_tokens;
CREATE POLICY "Users can view their own device tokens" ON public.notification_device_tokens FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own engagements" ON public.user_engagements;
CREATE POLICY "Users can view their own engagements" ON public.user_engagements FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own events" ON public.sanctuary_events;
CREATE POLICY "Users can view their own events" ON public.sanctuary_events FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own favorites" ON public.user_favorites;
CREATE POLICY "Users can view their own favorites" ON public.user_favorites FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own feedback" ON public.content_relevance_feedback;
CREATE POLICY "Users can view their own feedback" ON public.content_relevance_feedback FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own fitness scores" ON public.mental_fitness_scores;
CREATE POLICY "Users can view their own fitness scores" ON public.mental_fitness_scores FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own inner readiness scores" ON public.inner_readiness_scores;
CREATE POLICY "Users can view their own inner readiness scores" ON public.inner_readiness_scores FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own intervention events" ON public.micro_intervention_events;
CREATE POLICY "Users can view their own intervention events" ON public.micro_intervention_events FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own meta skill progress" ON public.meta_skill_progress;
CREATE POLICY "Users can view their own meta skill progress" ON public.meta_skill_progress FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own notification logs" ON public.notification_log;
CREATE POLICY "Users can view their own notification logs" ON public.notification_log FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own notification preferences" ON public.notification_preferences;
CREATE POLICY "Users can view their own notification preferences" ON public.notification_preferences FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own practice sessions" ON public.practice_sessions;
CREATE POLICY "Users can view their own practice sessions" ON public.practice_sessions FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own preferences" ON public.user_preferences;
CREATE POLICY "Users can view their own preferences" ON public.user_preferences FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (((auth.jwt() ->> 'sub') = id));
DROP POLICY IF EXISTS "Users can view their own ritual completions" ON public.daily_ritual_completions;
CREATE POLICY "Users can view their own ritual completions" ON public.daily_ritual_completions FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own saved debriefs" ON public.saved_debriefs;
CREATE POLICY "Users can view their own saved debriefs" ON public.saved_debriefs FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own session feedback" ON public.session_feedback;
CREATE POLICY "Users can view their own session feedback" ON public.session_feedback FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own snapshots" ON public.energy_snapshots;
CREATE POLICY "Users can view their own snapshots" ON public.energy_snapshots FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own tiny wins" ON public.tiny_wins;
CREATE POLICY "Users can view their own tiny wins" ON public.tiny_wins FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view their own wearable data" ON public.wearable_data;
CREATE POLICY "Users can view their own wearable data" ON public.wearable_data FOR SELECT USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can read own oura connection" ON public.oura_connections;
CREATE POLICY "Users can read own oura connection" ON public.oura_connections FOR SELECT TO authenticated USING ((user_id = (auth.jwt() ->> 'sub')));
DROP POLICY IF EXISTS "v8 onboarding: users select own" ON public.onboarding_v8_responses;
CREATE POLICY "v8 onboarding: users select own" ON public.onboarding_v8_responses FOR SELECT TO authenticated USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "v8 onboarding: users insert own" ON public.onboarding_v8_responses;
CREATE POLICY "v8 onboarding: users insert own" ON public.onboarding_v8_responses FOR INSERT TO authenticated WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "v8 onboarding: users update own" ON public.onboarding_v8_responses;
CREATE POLICY "v8 onboarding: users update own" ON public.onboarding_v8_responses FOR UPDATE TO authenticated USING (((auth.jwt() ->> 'sub') = user_id)) WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "v8 onboarding: users delete own" ON public.onboarding_v8_responses;
CREATE POLICY "v8 onboarding: users delete own" ON public.onboarding_v8_responses FOR DELETE TO authenticated USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own weekly snapshots" ON public.weekly_plan_snapshots;
CREATE POLICY "Users can view own weekly snapshots" ON public.weekly_plan_snapshots FOR SELECT TO authenticated USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can insert own weekly snapshots" ON public.weekly_plan_snapshots;
CREATE POLICY "Users can insert own weekly snapshots" ON public.weekly_plan_snapshots FOR INSERT TO authenticated WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can update own weekly snapshots" ON public.weekly_plan_snapshots;
CREATE POLICY "Users can update own weekly snapshots" ON public.weekly_plan_snapshots FOR UPDATE TO authenticated USING (((auth.jwt() ->> 'sub') = user_id)) WITH CHECK (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view own evaluator traces" ON public.notification_evaluator_traces;
CREATE POLICY "Users can view own evaluator traces" ON public.notification_evaluator_traces FOR SELECT TO authenticated USING (((auth.jwt() ->> 'sub') = user_id));
DROP POLICY IF EXISTS "Users can view runs with their traces" ON public.notification_evaluator_runs;
CREATE POLICY "Users can view runs with their traces" ON public.notification_evaluator_runs FOR SELECT TO authenticated USING ((EXISTS (SELECT 1 FROM public.notification_evaluator_traces t WHERE t.run_id = notification_evaluator_runs.id AND t.user_id = (auth.jwt() ->> 'sub'))));