// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apxvbknrnwevsawobvst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFweHZia25ybndldnNhd29idnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODIwMzcsImV4cCI6MjA2NjQ1ODAzN30.7ae9UBmpyyHmcVEtvdPyz5Ebr-vC-rk9f7OEJmohSEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);