// OWNERSHIP: coaching (subtype rows + keywords) + engineering (types).
// Granular CEO event subtypes — the 30 canonical rows that power JIT lead
// times, mastery scenario routing, demand-dimension scoring and intervention
// type per subtype. Each row references a category from ./event-categories.ts
// via `categoryId` (= the §3 framework pillar A–H).

import type { EventCategoryId, InterventionType } from "./event-categories.ts";

// ── Layer 1: Priority-state pillars (1–5) ─────────────────────────────
// Distinct axis from A–H. Engines (state-engines.ts) use these to score
// stakes and dominant-pillar. Kept on subtypes because the engine math
// depends on them.

export type Pillar = 1 | 2 | 3 | 4 | 5;

export interface PillarMeta {
  id: Pillar;
  name: string;
  priorityState: string;
  risks: string[];
  baseWeight: number;
}

export const PILLAR_META: Record<Pillar, PillarMeta> = {
  1: {
    id: 1,
    name: "Strategic Cognition",
    priorityState: "Flow + Clarity",
    risks: [
      "decision leakage",
      "cognitive overload",
      "narrowed thinking",
      "fatigue-driven simplification",
    ],
    baseWeight: 60,
  },
  2: {
    id: 2,
    name: "Executive Presence & Influence",
    priorityState: "Activated Calm",
    risks: [
      "adrenaline overshoot",
      "emotional hijack",
      "performance anxiety",
      "vocal/cognitive fatigue",
    ],
    baseWeight: 70,
  },
  3: {
    id: 3,
    name: "Emotional Load & Leadership Labor",
    priorityState: "Regulated Presence",
    risks: [
      "emotional leakage",
      "compassion fatigue",
      "suppression debt",
      "irritability carry-over",
    ],
    baseWeight: 65,
  },
  4: {
    id: 4,
    name: "Operational Pressure & Execution",
    priorityState: "Controlled Output",
    risks: [
      "attentional fragmentation",
      "NS overload",
      "stress accumulation",
      "reactive lock",
    ],
    baseWeight: 40,
  },
  5: {
    id: 5,
    name: "Recovery & Reintegration",
    priorityState: "Downregulation + Reset",
    risks: [
      "post-adrenaline crash",
      "emotional residue",
      "sleep disruption",
      "cognitive fatigue debt",
    ],
    baseWeight: 0,
  },
};

// ── Demand profile ────────────────────────────────────────────────────

export type DemandDim =
  | "cog"
  | "emo"
  | "vis"
  | "pol"
  | "rel"
  | "ene"
  | "cir"
  | "id";
export type DemandProfile = Record<DemandDim, 0 | 1 | 2 | 3>;

const D = (
  cog: number,
  emo: number,
  vis: number,
  pol: number,
  rel: number,
  ene: number,
  cir: number,
  id: number,
): DemandProfile =>
  ({ cog, emo, vis, pol, rel, ene, cir, id }) as DemandProfile;

export function demandSum(p: DemandProfile): number {
  return p.cog + p.emo + p.vis + p.pol + p.rel + p.ene + p.cir + p.id;
}

// ── Subtype shape ─────────────────────────────────────────────────────

export type EventGroup =
  | "A_governance"
  | "B_investor"
  | "C_strategic"
  | "D_visibility"
  | "E_leadership"
  | "F_operational"
  | "G_travel"
  | "H_recovery";

export type RegulationObjective = "PREPARE" | "PREVENT" | "PROTECT" | "RECOVER";

export interface TimingMatrix {
  pre: boolean;
  during: boolean;
  post: boolean;
  postMandatory?: boolean;
}

export interface EventType {
  id: string;
  label: string;
  /** Bucket label compatible with causality_findings.signal_summary store. */
  bucket: string;
  /** Legacy group code preserved for backwards-compat with downstream maps. */
  group: EventGroup;
  /**
   * Canonical category (A–H) from ./event-categories.ts. New name for what
   * was `frameworkPillar` — both fields are populated for one release.
   */
  categoryId: EventCategoryId;
  /** @deprecated Use categoryId. Kept for backwards-compat. */
  frameworkPillar: EventCategoryId;
  primaryPillar: Pillar;
  secondaryPillar?: Pillar;
  demandProfile: DemandProfile;
  timingMatrix: TimingMatrix;
  regulationObjective: RegulationObjective;
  interventionType: InterventionType;
  keywords: string[];
  masteryModules?: string[];
  jitLeadTimeMinutes?: number;
  /** Classification-only — no JIT, nudges or mastery (e.g. Networking). */
  classificationOnly?: boolean;
  /**
   * Optional v2-only field. Substring tokens (lowercased) that, when present
   * in the title, disqualify a match on `keywords`. Honoured by
   * classify-event-v2's Layer 6 word-boundary dictionary match. The legacy
   * `classifyEvent` ignores it for backwards compatibility.
   */
  excludeKeywords?: string[];
  /**
   * Optional AND-matching cues. Each group is a list of tokens that must ALL
   * be present in the (lowercased) title for the row to match. Used where a
   * single substring is ambiguous — e.g. "roundtable" is E.community when the
   * user is a member but C.roundtable when they are speaking at it.
   */
  keywordGroups?: string[][];
}

// Helper to keep rows compact + auto-mirror categoryId/frameworkPillar.
type RawSubtype = Omit<EventType, "frameworkPillar"> & {
  categoryId: EventCategoryId;
};
const ROWS: RawSubtype[] = [
  // ── Category A · Board & Governance ──
  // v2 additive — school/nonprofit governance. MUST precede gov.board_meeting so
  // "school board" / "trustee" don't fall into the corporate board bucket.
  {
    id: "gov.trustee",
    label: "Trustee / School board / Nonprofit board",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "A_governance",
    primaryPillar: 3,
    secondaryPillar: 1,
    demandProfile: D(2, 2, 1, 2, 3, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "governor role",
      "trustee",
      "school board",
      "school governor",
      "nonprofit board",
      "charity board",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "gov.board_meeting",
    label: "Board meeting",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "A_governance",
    primaryPillar: 1,
    secondaryPillar: 2,
    demandProfile: D(3, 1, 3, 3, 1, 2, 0, 3),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: ["board meeting", "board of directors", "board"],
    excludeKeywords: [
      "board prep",
      "board prep test",
      "onboarding",
      "off-boarding",
      "offboarding",
      "keyboard",
      "cardboard",
      "surfboard",
      "dashboard",
      "whiteboard",
      "starboard",
      "overboard",
      "aboard",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  {
    id: "gov.board_committee",
    label: "Board committee",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "A_governance",
    primaryPillar: 1,
    secondaryPillar: 2,
    demandProfile: D(3, 1, 2, 3, 1, 1, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "audit committee",
      "remco",
      "nomco",
      "board committee",
      "governance",
    ],
  },
  {
    id: "gov.board_prep",
    label: "Board prep",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "A_governance",
    primaryPillar: 1,
    demandProfile: D(3, 0, 1, 2, 0, 1, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "board deck",
      "board prep",
      "board presentation",
      "board materials",
    ],
    excludeKeywords: ["board prep test"],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 2880,
  },
  // ── Additive row for v2 acronym dictionary ──
  {
    id: "gov.nonexec_board",
    label: "Non-exec board / NED meeting",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "A_governance",
    primaryPillar: 1,
    secondaryPillar: 2,
    demandProfile: D(2, 1, 2, 3, 2, 1, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "non-exec board",
      "nonexec board",
      "ned meeting",
      "non-executive director",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  {
    id: "gov.investor_meeting",
    label: "Investor meeting",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "B_investor",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(2, 2, 3, 2, 1, 2, 0, 3),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: ["investor", "vc ", " vc", "lp meeting", "limited partner"],
    masteryModules: ["regulate", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  {
    id: "gov.earnings_call",
    label: "Earnings call",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "B_investor",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(3, 1, 3, 2, 0, 2, 0, 3),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: ["earnings call", "earnings"],
  },
  {
    id: "gov.qbr",
    label: "QBR / Quarterly review",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "C_strategic",
    primaryPillar: 1,
    secondaryPillar: 4,
    demandProfile: D(3, 1, 2, 2, 2, 2, 0, 2),
    timingMatrix: { pre: true, during: true, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "quarterly",
      "qbr",
      "q1 review",
      "q2 review",
      "q3 review",
      "q4 review",
    ],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 2880,
  },
  {
    id: "gov.budget_review",
    label: "Budget / forecast review",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "B_investor",
    primaryPillar: 1,
    demandProfile: D(3, 1, 1, 2, 1, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: ["budget", "finance review", "forecast", "financial planning"],
    excludeKeywords: ["budget review"],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  {
    id: "gov.ma_discussion",
    label: "M&A discussion",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "B_investor",
    primaryPillar: 1,
    secondaryPillar: 2,
    demandProfile: D(3, 2, 2, 3, 1, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: ["m&a", "merger", "acquisition", "due diligence", "acqui-hire"],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 2880,
  },
  {
    id: "gov.crisis",
    label: "Crisis / Incident",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "F_operational",
    primaryPillar: 4,
    secondaryPillar: 3,
    demandProfile: D(3, 3, 2, 2, 2, 3, 0, 2),
    timingMatrix: { pre: false, during: true, post: true, postMandatory: true },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: ["crisis", "urgent", "emergency", "incident", "escalation"],
    masteryModules: ["regulate"],
    jitLeadTimeMinutes: 120,
  },

  // ── Category B · Influence & Persuasion ──
  // v2 additive — competitive pitch (bake-off / RFP). Insert BEFORE inf.fundraising
  // so a "pitch to L'Oreal" is not routed to fundraising.
  {
    id: "inf.pitch_competitive",
    label: "Competitive pitch / RFP",
    bucket: "Influence & Persuasion",
    categoryId: "B",
    group: "B_investor",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(2, 2, 3, 2, 1, 3, 0, 3),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "pitch to ",
      "competitive pitch",
      "bake-off",
      "bake off",
      "rfp presentation",
      "rfp pitch",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "inf.fundraising",
    label: "Fundraising / Pitch",
    bucket: "Influence & Persuasion",
    categoryId: "B",
    group: "B_investor",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(2, 2, 3, 2, 1, 3, 0, 3),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "fundraise",
      "fundraising",
      "raise",
      "pitch deck",
      "pitch",
      "funding",
    ],
    excludeKeywords: ["review", "pitch deck review", "pitch deck - review"],
  },
  {
    id: "inf.negotiation",
    label: "Negotiation",
    bucket: "Influence & Persuasion",
    categoryId: "B",
    group: "E_leadership",
    primaryPillar: 2,
    secondaryPillar: 3,
    demandProfile: D(2, 2, 1, 3, 2, 2, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: ["negotiation", "contract", "deal terms", "partnership terms"],
    masteryModules: ["regulate", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "inf.client_presentation",
    label: "Client / customer presentation",
    bucket: "Influence & Persuasion",
    categoryId: "B",
    group: "D_visibility",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(2, 1, 2, 1, 2, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "client",
      "customer",
      "demo",
      "proposal",
      "account review",
      "stakeholder",
      "presenting",
      "present to",
      "presentation",
      "introduction to mind module",
      "mind module narrative",
    ],
    excludeKeywords: [
      "presentation deck review",
      "presentation prep",
      "board presentation",
      "board materials",
      "dashboard",
      "customer support",
      "presenting strategy",
      "strategy planning",
      "strategic planning",
      "do's and don'ts",
      "dos and donts",
      "webinar",
      "masterclass",
      "q1 presentation",
      "q2 presentation",
      "q3 presentation",
      "q4 presentation",
    ],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 480,
  },

  // ── Category C · Visibility & Communication ──
  // Spec C.roundtable — user is SPEAKING / PRESENTING at a roundtable.
  // Must precede str.community, which owns the "member of" case.
  {
    id: "vis.roundtable",
    label: "Roundtable (speaking)",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 3, 1, 1, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "speaking at roundtable",
      "roundtable panel",
      "moderating roundtable",
      "chairing roundtable",
      "roundtable keynote",
    ],
    keywordGroups: [
      ["roundtable", "speaking"],
      ["roundtable", "moderat"],
      ["roundtable", "chairing"],
      ["roundtable", "presenting"],
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },

  // v2 additive — internal stakeholder / results communication. Insert BEFORE vis.media/all_hands
  // so titles like "Q2 results to leadership" route here rather than to media or fundraising.
  {
    id: "vis.stakeholder_comm",
    label: "Stakeholder communication",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    secondaryPillar: 1,
    demandProfile: D(2, 1, 3, 2, 2, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "results to leadership",
      "update to leadership",
      "exec update",
      "leadership update",
      "results presentation",
      "q1 presentation",
      "q2 presentation",
      "q3 presentation",
      "q4 presentation",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 360,
  },
  {
    id: "vis.media",
    label: "Media / Press / Podcast",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(2, 1, 3, 1, 1, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "media interview",
      "press interview",
      "podcast interview",
      "podcast",
      "media",
      "press",
      "journalist",
      "pr ",
    ],
    excludeKeywords: [
      "immediate",
      "immediately",
      "intermediate",
      "social media",
      "media query",
      "impress",
      "expression",
      "depressed",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 360,
  },
  {
    id: "vis.all_hands",
    label: "All-hands / Town hall",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    secondaryPillar: 3,
    demandProfile: D(1, 2, 3, 1, 2, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Reenergise",
    keywords: [
      "all-hands",
      "all hands",
      "town hall",
      "townhall",
      "company meeting",
    ],
    masteryModules: ["regulate", "align"],
    jitLeadTimeMinutes: 240,
  },
  // ── Category D · Interpersonal High-Stakes ──
  {
    id: "lead.executive_1on1",
    label: "Executive 1:1",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    demandProfile: D(1, 2, 1, 1, 3, 1, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: ["1:1", "1-1", "one on one", "1on1"],
  },
  // NOTE: bare 'ceo'/'cto'/'exec' tokens removed — they collide with titles
  // like "Interview with EY CEO" which must classify as hiring_committee, not
  // leadership_sync. Keep multi-word tokens that genuinely denote a sync.
  {
    id: "lead.leadership_sync",
    label: "Leadership / Exec team sync",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    secondaryPillar: 1,
    demandProfile: D(2, 1, 1, 2, 2, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "leadership team",
      "exec team",
      "c-suite",
      "slt",
      "elt",
      "management meeting",
      "leadership sync",
      "leadership offsite",
      "exec sync",
      "executive sync",
      "executive committee",
    ],
    masteryModules: ["regulate", "align"],
    jitLeadTimeMinutes: 240,
  },
  {
    id: "lead.performance_review",
    label: "Performance review",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    secondaryPillar: 1,
    demandProfile: D(2, 3, 1, 2, 3, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "performance review",
      "annual review",
      "mid-year review",
      "360 feedback",
      "360 review",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 480,
  },
  // v2 fix — 'feedback' keyword was routing "Beta test feedback" (deep work review) to D.
  // excludeKeywords now suppress the deep-work / product-feedback family.
  {
    id: "lead.difficult_conversation",
    label: "Difficult conversation / Escalation",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    demandProfile: D(1, 3, 1, 2, 3, 2, 0, 1),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "difficult",
      "feedback",
      "pip",
      "conflict",
      "dispute",
      "tension",
      "confrontation",
      "escalation",
    ],
    excludeKeywords: [
      "pipeline",
      "pipe ",
      "pipework",
      "feedback loop",
      "feedback form",
      "beta feedback",
      "beta test feedback",
      "feedback session",
      "feedback review",
      "user feedback",
      "customer feedback",
      "product feedback",
      "feedback analysis",
    ],
    masteryModules: ["regulate", "prepare"],
    jitLeadTimeMinutes: 240,
  },
  {
    id: "lead.layoff",
    label: "Layoff / Restructure",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    secondaryPillar: 2,
    demandProfile: D(1, 3, 2, 2, 3, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "layoff",
      "restructuring",
      "restructure",
      "reduction",
      "rif",
      "downsizing",
      "termination",
    ],
    masteryModules: ["regulate", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  // v2 additive — candidate-side / screening interview split. Insert BEFORE hiring_committee.
  {
    id: "lead.hiring_interview",
    label: "Hiring interview (candidate)",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    secondaryPillar: 1,
    demandProfile: D(2, 1, 1, 1, 2, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "screening interview",
      "screening call",
      "candidate screen",
      "phone screen",
      "interview with ",
    ],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 240,
  },
  {
    id: "lead.hiring_committee",
    label: "Job interview / Hiring committee",
    bucket: "Interpersonal High-Stakes",
    categoryId: "D",
    group: "E_leadership",
    primaryPillar: 3,
    secondaryPillar: 1,
    demandProfile: D(2, 1, 1, 1, 2, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "job interview",
      "final round interview",
      "final round",
      "hiring committee",
      "offer discussion",
      "executive hire",
      "candidate",
      "interview",
    ],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 240,
  },

  // ── Category E · Deep Work & Strategy ──
  // v2 additive rows. Insert BEFORE existing E rows AND before conf.speaking so
  // "webinar"/"masterclass" etc. do not fall through to F.speaking or B.pitch.
  {
    id: "str.learning",
    label: "Learning / Passive attendee",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "C_strategic",
    primaryPillar: 1,
    demandProfile: D(1, 0, 0, 0, 1, 1, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Flow",
    keywords: [
      "webinar",
      "masterclass",
      "fireside chat",
      "online course",
      "online class",
      "learn to",
      "psychology of",
      "what really",
      "what it takes",
      "what actually",
      "sales assumptions",
      "do's and don'ts",
      "dos and donts",
      "new biz presentations",
      "cracking the us market",
      "intro call >",
    ],
    excludeKeywords: [
      "hosting webinar",
      "running webinar",
      "delivering masterclass",
      "client presentation",
      "customer presentation",
    ],
    classificationOnly: true,
  },
  {
    id: "str.community",
    label: "Community / Member group",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "C_strategic",
    primaryPillar: 3,
    demandProfile: D(1, 1, 1, 0, 3, 1, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "breakfast club",
      "banking on breakfast",
      "thursday connects",
      "chief ai thursday",
      "chapter meeting",
      "network group",
      "community forum",
      "member group",
      "members meeting",
      "roundtable",
      "forum",
      "connects",
      "power sisters",
      "diversity & inclusion",
    ],
    classificationOnly: true,
  },
  {
    id: "str.review",
    label: "Review (BP / product / design / sprint)",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "C_strategic",
    primaryPillar: 1,
    secondaryPillar: 4,
    demandProfile: D(2, 1, 1, 1, 2, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "bp review",
      "budget review",
      "product review",
      "design review",
      "sprint review",
      "retro",
      "retrospective",
    ],
    excludeKeywords: [
      "board",
      "investor",
      "performance review",
      "annual review",
      "mid-year review",
    ],
    masteryModules: ["prepare"],
    jitLeadTimeMinutes: 240,
  },
  {
    id: "str.compliance",
    label: "Compliance / Legal / Filing",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "C_strategic",
    primaryPillar: 1,
    demandProfile: D(2, 0, 0, 1, 1, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: false },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "uk filing",
      "visa appointment",
      "compliance review",
      "legal review",
      "audit review",
      "tax filing",
      "regulatory filing",
    ],
    excludeKeywords: ["audit committee"],
    masteryModules: ["prepare"],
    jitLeadTimeMinutes: 240,
  },
  {
    id: "str.strategy_planning",
    label: "Strategy planning",
    bucket: "Board & Governance",
    categoryId: "A",
    group: "C_strategic",
    primaryPillar: 1,
    demandProfile: D(3, 0, 1, 1, 1, 1, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: [
      "strategy",
      "strategic planning",
      "vision",
      "roadmap",
      "annual operating plan",
      "3-year plan",
      "3 year plan",
    ],
    // Deep-work blocks that merely mention strategy stay in E.
    excludeKeywords: ["deep work", "focus block", "writing time", "strategy review"],
    masteryModules: ["align", "prepare"],
    jitLeadTimeMinutes: 1440,
  },
  // v2 — added positive keywords for beta/product feedback review (previously mis-routed to D).
  {
    id: "str.deep_work",
    label: "Deep work block",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "C_strategic",
    primaryPillar: 1,
    demandProfile: D(3, 0, 0, 0, 0, 1, 0, 0),
    timingMatrix: { pre: true, during: true, post: true },
    regulationObjective: "PROTECT",
    interventionType: "Flow",
    keywords: [
      "deep work",
      "focus block",
      "writing time",
      "beta test feedback",
      "beta feedback",
      "feedback review",
      "feedback analysis",
      "feedback session",
      "user feedback",
      "customer feedback",
      "product feedback",
      "board prep",
      "strategy review",
      "pitch deck review",
      "pitch deck - review",
    ],
  },
  {
    id: "str.product_launch",
    label: "Product launch / Go-live",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "F_operational",
    primaryPillar: 4,
    secondaryPillar: 2,
    demandProfile: D(2, 2, 2, 1, 2, 3, 0, 2),
    timingMatrix: { pre: true, during: true, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Flow",
    keywords: ["launch", "go live", "release", "ship", "product launch"],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 1440,
  },

  // ── Category F · Conferences & External Events ──
  {
    id: "conf.keynote",
    label: "Keynote",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 3, 1, 0, 3, 0, 3),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: ["keynote"],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  // v2 — 'webinar' and 'roundtable' removed; now owned by str.learning / str.community.
  // Also 'fireside' removed (fireside chat = passive attendee); keep only speaker-lead cues.
  {
    id: "conf.speaking",
    label: "Conference speaking / Panel",
    bucket: "Visibility & Communication",
    categoryId: "C",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 3, 1, 0, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "conference",
      "summit",
      "panel discussion",
      "panel",
      "speaking engagement",
      "speaker slot",
    ],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "conf.offsite",
    label: "Off-site / Retreat",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    secondaryPillar: 3,
    demandProfile: D(2, 2, 2, 1, 3, 3, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: ["offsite", "off-site", "retreat"],
    masteryModules: ["regulate", "align"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "conf.award",
    label: "Award / Recognition event",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 3, 0, 1, 2, 0, 2),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: ["award", "recognition event", "awards ceremony", "gala"],
  },
  {
    id: "conf.customer_summit",
    label: "Customer / partner summit",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    secondaryPillar: 3,
    demandProfile: D(2, 1, 2, 1, 3, 3, 0, 2),
    timingMatrix: { pre: true, during: false, post: true, postMandatory: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: ["customer summit", "partner summit", "user conference"],
    masteryModules: ["regulate", "align", "prepare"],
    jitLeadTimeMinutes: 720,
  },
  {
    id: "conf.networking",
    label: "Networking event",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(0, 1, 1, 0, 2, 1, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "networking event",
      "networking dinner",
      "networking drinks",
      "meetup",
      "mixer",
    ],
    classificationOnly: true,
  },
  // Spec F.workshop — all-day / multi-day workshop, open evening, open day.
  {
    id: "conf.workshop",
    label: "Workshop / Open day",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 1, 0, 2, 2, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "open evening",
      "open day",
      "all-day workshop",
      "multi-day workshop",
    ],
    classificationOnly: true,
  },
  // Spec F.event — multi-day event (expo, festival, show, fair).
  {
    id: "conf.event",
    label: "Multi-day event",
    bucket: "Conferences & External Events",
    categoryId: "F",
    group: "D_visibility",
    primaryPillar: 2,
    demandProfile: D(1, 1, 1, 0, 2, 2, 0, 1),
    timingMatrix: { pre: true, during: false, post: true },
    regulationObjective: "PREPARE",
    interventionType: "Pause",
    keywords: [
      "expo",
      "schools show",
      "summer fair",
      "trade show",
    ],
    classificationOnly: true,
  },

  // ── Category G · Travel ──
  {
    id: "trv.long_haul",
    label: "Long-haul flight",
    bucket: "Travel",
    categoryId: "G",
    group: "G_travel",
    primaryPillar: 4,
    secondaryPillar: 5,
    demandProfile: D(1, 1, 0, 0, 0, 3, 3, 0),
    timingMatrix: { pre: true, during: true, post: true, postMandatory: true },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "long-haul",
      "long haul",
      "red-eye",
      "redeye",
      "overnight flight",
    ],
  },
  // NOTE: bare 'transit' removed — it sub-string matches "transition", causing
  // recurring leadership titles like "Chief UK In Transition" to be tagged as
  // travel. Keep concrete travel tokens only.
  {
    id: "trv.flight",
    label: "Flight / Travel",
    bucket: "Travel",
    categoryId: "G",
    group: "G_travel",
    primaryPillar: 4,
    secondaryPillar: 5,
    demandProfile: D(1, 1, 0, 0, 0, 2, 2, 0),
    timingMatrix: { pre: true, during: true, post: true },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "flight",
      "airport",
      "boarding",
      "departure",
      "arrival",
      "layover",
      "in transit",
    ],
    excludeKeywords: [
      "onboarding",
      "off-boarding",
      "offboarding",
      "flight showcase",
      "flight deck review",
      "flight risk",
      "test flight",
      "transition",
    ],
  },
  // v2 additive — accommodation & full travel-day markers. Classification-only
  // (they inform Insights and Plan arc selection; no JIT prompts on their own).
  {
    id: "trv.accommodation",
    label: "Accommodation / Hotel",
    bucket: "Travel",
    categoryId: "G",
    group: "G_travel",
    primaryPillar: 4,
    secondaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 1, 1, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "hotel booking",
      "hotel stay",
      "airbnb",
      "staying at",
      "accommodation",
      "hotel reservation",
      "stay at",
      "stay:",
      "hotel",
      "resort",
      "guesthouse",
      "narrowboat stay",
      "check-in hotel",
    ],
    classificationOnly: true,
  },
  {
    id: "trv.travel_day",
    label: "Travel day",
    bucket: "Travel",
    categoryId: "G",
    group: "G_travel",
    primaryPillar: 4,
    secondaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 2, 2, 0),
    timingMatrix: { pre: true, during: true, post: true },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "travel day",
      "in transit day",
      "all-day travel",
      "all day travel",
      "travel to",
      "sightseeing",
      "guided tour",
      "city tour",
      "island tour",
      // Landmark / excursion titles that carry no explicit "tour" token.
      "statue of liberty",
      "ellis island",
      "elise island",
      "day trip",
      "excursion",
      "boat tour",
      "ferry to",
      "harbour cruise",
      "harbor cruise",
    ],
    classificationOnly: true,
  },

  // ── Category H · Daily Rhythm & Baseline ──
  // v2 additive — insert BEFORE rhy.catchup / rhy.pto so more specific rows win
  // when keywords overlap (e.g. rhy.pto has 'holiday' — rhy.holiday must precede it).
  {
    id: "rhy.holiday",
    label: "Public / bank holiday",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "RECOVER",
    interventionType: "Pause",
    keywords: [
      "bank holiday",
      "public holiday",
      "national holiday",
      "federal holiday",
      "national day",
      "day observed",
      "harmony day",
      "flag day",
      "vesak",
      "ashura",
      "armed forces day",
      "ratha yatra",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.wellness_fitness",
    label: "Wellness — fitness",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 1, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "RECOVER",
    interventionType: "Pause",
    keywords: [
      "gym",
      "workout",
      "yoga class",
      "pilates",
      "spin class",
      "swim session",
      "running club",
      "cycling class",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.wellness_self_care",
    label: "Wellness — self care",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "RECOVER",
    interventionType: "Pause",
    keywords: [
      "massage",
      "spa appointment",
      "manicure",
      "pedicure",
      "facial appointment",
      "salon appointment",
      "spa day",
      "liquid fast",
      "water fast",
      "fasting",
      "day fast",
      "detox",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.wellness_health_check",
    label: "Wellness — health check",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 1, 0, 0, 0, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "weigh day",
      "weigh-in",
      "blood test",
      "health check",
      "physical exam",
      "annual physical",
      "medical check",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.wellness_medical",
    label: "Wellness — medical appointment",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 1, 0, 0, 0, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "doctor appointment",
      "dentist appointment",
      "physio",
      "physiotherapy",
      "osteopath",
      "chiropractor",
      "gp appointment",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.social",
    label: "Personal social",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 1, 0, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "coffee with",
      "drinks with",
      "dinner with",
      "beer with",
      "brunch with",
      "walk with",
      "chat with",
      "chat ",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.family",
    label: "Family / Personal",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 1, 0, 0, 2, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "birthday",
      "anniversary",
      "family dinner",
      "school play",
      "school pickup",
      "school fair",
      "kids party",
      "wedding",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.recreation",
    label: "Recreation / Culture",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 0, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "RECOVER",
    interventionType: "Pause",
    keywords: [
      "concert",
      "matinee",
      "opera",
      "ballet",
      "theatre show",
      "theater show",
      "festival",
      "stars on ice",
      "reservation at",
      "dinner at",
      "table at",
      "museum",
      "exhibition",
      "cinema",
    ],
    classificationOnly: true,
  },
  {
    id: "rhy.catchup",
    label: "Routine sync / Catch-up",
    bucket: "Deep Work & Strategy",
    categoryId: "E",
    group: "F_operational",
    primaryPillar: 4,
    demandProfile: D(1, 1, 0, 0, 2, 1, 0, 0),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "PROTECT",
    interventionType: "Pause",
    keywords: [
      "catchup",
      "catch-up",
      "catch up",
      "sync",
      "check-in",
      "check in",
      "weekly",
      "standup",
      "stand-up",
    ],
    excludeKeywords: [
      "forum",
      "roundtable",
      "community",
      "connects",
    ],
  },
  {
    id: "rhy.pto",
    label: "PTO / Time off",
    bucket: "Daily Rhythm & Baseline",
    categoryId: "H",
    group: "H_recovery",
    primaryPillar: 5,
    demandProfile: D(0, 0, 0, 0, 0, 0, 0, 1),
    timingMatrix: { pre: false, during: false, post: false },
    regulationObjective: "RECOVER",
    interventionType: "Pause",
    keywords: [
      "out of office",
      "ooo",
      "annual leave",
      "holiday",
      "vacation",
      "pto",
      "day off",
      "away",
    ],
  },
];

export const EVENT_TYPES: EventType[] = ROWS.map((r) => ({
  ...r,
  frameworkPillar: r.categoryId,
}));

// ── EVENT_TYPE → mastery scenarioId ──────────────────────────────────
export const EVENT_TYPE_TO_SCENARIO_ID: Record<string, string | null> = {
  "gov.board_meeting": "pre-board-meeting",
  "gov.board_committee": "pre-board-meeting",
  "gov.board_prep": "pre-board-meeting",
  "gov.investor_meeting": "pre-investor-meeting",
  "gov.earnings_call": "pre-budget-review",
  "gov.qbr": "pre-quarterly-review",
  "gov.budget_review": "pre-budget-review",
  "gov.ma_discussion": "pre-negotiations",
  "gov.crisis": "pre-crisis-response",
  "gov.trustee": "pre-board-meeting",
  "inf.pitch_competitive": "pre-client-presentation",
  "inf.fundraising": "pre-investor-meeting",
  "inf.negotiation": "pre-negotiations",
  "inf.client_presentation": "pre-client-presentation",
  "vis.stakeholder_comm": "pre-all-hands",
  "vis.media": "pre-media",
  "vis.all_hands": "pre-all-hands",
  "lead.executive_1on1": null,
  "lead.leadership_sync": "pre-all-hands",
  "lead.performance_review": "pre-performance-review",
  "lead.difficult_conversation": "pre-difficult-conversation",
  "lead.layoff": "pre-difficult-conversation",
  "lead.hiring_interview": "pre-hiring-decision",
  "lead.hiring_committee": "pre-hiring-decision",
  "str.strategy_planning": "pre-strategic-planning",
  "str.deep_work": null,
  "str.learning": null,
  "str.community": null,
  "str.review": "pre-strategic-planning",
  "str.compliance": null,
  "str.product_launch": "pre-strategic-planning",
  "conf.keynote": "pre-speaking-engagement",
  "conf.speaking": "pre-speaking-engagement",
  "conf.offsite": "pre-strategic-planning",
  "conf.award": "pre-speaking-engagement",
  "conf.customer_summit": "pre-speaking-engagement",
  "conf.networking": null,
  "trv.long_haul": null,
  "trv.flight": null,
  "trv.accommodation": null,
  "trv.travel_day": null,
  "rhy.catchup": null,
  "rhy.pto": null,
  "rhy.holiday": null,
  "rhy.wellness_fitness": null,
  "rhy.wellness_self_care": null,
  "rhy.wellness_health_check": null,
  "rhy.wellness_medical": null,
  "rhy.social": null,
  "rhy.family": null,
  "rhy.recreation": null,
};
