import type { EventCategoryId } from "./event-categories.ts";

export interface GoldenEventCase {
  id: string;
  title: string;
  description?: string | null;
  attendees?: Array<{
    name?: string | null;
    email?: string | null;
    domain?: string | null;
    isSelf?: boolean;
    isOrganizer?: boolean;
  }>;
  location?: string | null;
  durationMinutes?: number | null;
  isRecurring?: boolean;
  expectedCategory: EventCategoryId;
  expectedSubtype?: string | null;
  difficulty: "obvious" | "ambiguous" | "misleading_title" | "edge_case";
  categoryGroup: string;
  notes?: string;
}

export const GOLDEN_SET: GoldenEventCase[] = [
  // ── CATEGORY A: Board & Governance (20 cases) ────────────────────────
  { id: "gold_a_01", title: "Q3 Board of Directors Meeting", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_02", title: "Audit & Risk Committee", expectedCategory: "A", expectedSubtype: "gov.committee", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_03", title: "Remuneration Committee Review", expectedCategory: "A", expectedSubtype: "gov.committee", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_04", title: "Annual General Meeting (AGM)", expectedCategory: "A", expectedSubtype: "gov.agm", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_05", title: "Board Strategy Offsite", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_06", title: "3-year strategy planning", expectedCategory: "A", expectedSubtype: "str.strategy_planning", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_07", title: "Investor Update — Board of Advisors", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_08", title: "Governance and Nominations Committee", expectedCategory: "A", expectedSubtype: "gov.committee", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_09", title: "Board Chair Monthly Catchup", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_10", title: "Extraordinary General Meeting (EGM)", expectedCategory: "A", expectedSubtype: "gov.agm", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_11", title: "Q4 Financial Budget Approval", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_12", title: "Statutory Director Review", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_13", title: "Shareholder Strategy Briefing", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_14", title: "Advisory Board Quarterly Session", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_15", title: "Long-term Capital Strategy Review", expectedCategory: "A", expectedSubtype: "str.strategy_planning", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_16", title: "Board Governance Policy Signoff", expectedCategory: "A", expectedSubtype: "gov.committee", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_17", title: "Investor Board Briefing — Series B", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "ambiguous", categoryGroup: "governance" },
  { id: "gold_a_18", title: "Special Board Session: M&A Authorization", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_19", title: "Trustee Board Quarterly Meeting", expectedCategory: "A", expectedSubtype: "gov.board_meeting", difficulty: "obvious", categoryGroup: "governance" },
  { id: "gold_a_20", title: "Company Strategic Planning 2027", expectedCategory: "A", expectedSubtype: "str.strategy_planning", difficulty: "obvious", categoryGroup: "governance" },

  // ── CATEGORY B: Pitches, Deals & Negotiations (20 cases) ──────────────
  { id: "gold_b_01", title: "Product Demo & Commercial Pitch", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_02", title: "Rick Meeting with Shukrita Puri and Geeta Puri from Mind Module", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "edge_case", categoryGroup: "pitch_deal" },
  { id: "gold_b_03", title: "Enterprise Contract Negotiation", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_04", title: "Series A Pitch: Sequoia Capital", expectedCategory: "B", expectedSubtype: "inf.pitch", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_05", title: "Commercial Terms Finalisation", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_06", title: "Client Discovery & Solution Demo", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_07", title: "Vendor Pricing & SLA Negotiation", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_08", title: "Prospect Demo: St Paul's School", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "ambiguous", categoryGroup: "pitch_deal" },
  { id: "gold_b_09", title: "Strategic Partnership Pitch", expectedCategory: "B", expectedSubtype: "inf.partnership", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_10", title: "Enterprise Master Services Agreement Discussion", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_11", title: "Pitch to Accel Partners", expectedCategory: "B", expectedSubtype: "inf.pitch", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_12", title: "Software License Renewal Deal", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "ambiguous", categoryGroup: "pitch_deal" },
  { id: "gold_b_13", title: "Sales Presentation — EMEA Expansion", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_14", title: "Commercial Closing Call with Buyer", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_15", title: "B2B SaaS Term Sheet Discussion", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_16", title: "Client Capability Pitch", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_17", title: "JV Terms Negotiation with Partner", expectedCategory: "B", expectedSubtype: "inf.partnership", difficulty: "ambiguous", categoryGroup: "pitch_deal" },
  { id: "gold_b_18", title: "Procurement Vendor Review Meeting", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "ambiguous", categoryGroup: "pitch_deal" },
  { id: "gold_b_19", title: "Venture Debt Terms Discussion", expectedCategory: "B", expectedSubtype: "inf.commercial_negotiation", difficulty: "obvious", categoryGroup: "pitch_deal" },
  { id: "gold_b_20", title: "RFP Finalist Presentation to Client", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "obvious", categoryGroup: "pitch_deal" },

  // ── CATEGORY C: Public Speaking & Media (20 cases) ───────────────────
  { id: "gold_c_01", title: "Keynote at Founder Summit", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_02", title: "Speaking at the AI leaders roundtable", expectedCategory: "C", expectedSubtype: "vis.roundtable", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_03", title: "Company All Hands — Q3 Vision", expectedCategory: "C", expectedSubtype: "vis.all_hands", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_04", title: "Bloomberg TV Live Interview", expectedCategory: "C", expectedSubtype: "vis.media_interview", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_05", title: "Town Hall: Company Strategy Update", expectedCategory: "C", expectedSubtype: "vis.all_hands", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_06", title: "Podcast Guest: High Performance Leadership", expectedCategory: "C", expectedSubtype: "vis.media_interview", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_07", title: "Fireside Chat at TechCrunch Disrupt", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_08", title: "Panel Speaker: Future of Executive Health", expectedCategory: "C", expectedSubtype: "conf.panelist", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_09", title: "Press Briefing — Product V2 Launch", expectedCategory: "C", expectedSubtype: "vis.press_briefing", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_10", title: "FT Interview on Mental Fitness", expectedCategory: "C", expectedSubtype: "vis.media_interview", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_11", title: "Guest Lecture at London Business School", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "ambiguous", categoryGroup: "speaking" },
  { id: "gold_c_12", title: "Webinar Presentation: Scaling Mindsets", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "ambiguous", categoryGroup: "speaking" },
  { id: "gold_c_13", title: "Industry Roundtable: Chief People Officers", expectedCategory: "C", expectedSubtype: "vis.roundtable", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_14", title: "Staff Townhall Q&A", expectedCategory: "C", expectedSubtype: "vis.all_hands", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_15", title: "Keynote Address: EdTech Global Congress", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_16", title: "Journalist Briefing: Annual Insights Report", expectedCategory: "C", expectedSubtype: "vis.press_briefing", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_17", title: "Live Streaming AMA with CEO", expectedCategory: "C", expectedSubtype: "vis.all_hands", difficulty: "ambiguous", categoryGroup: "speaking" },
  { id: "gold_c_18", title: "Forbes Profile Interview", expectedCategory: "C", expectedSubtype: "vis.media_interview", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_19", title: "External Keynote: Leadership Resilience", expectedCategory: "C", expectedSubtype: "conf.keynote", difficulty: "obvious", categoryGroup: "speaking" },
  { id: "gold_c_20", title: "Broadcast Recording: Thought Leadership Series", expectedCategory: "C", expectedSubtype: "vis.media_interview", difficulty: "ambiguous", categoryGroup: "speaking" },

  // ── CATEGORY D: People & Team Dynamics (20 cases) ────────────────────
  { id: "gold_d_01", title: "1:1 with VP Engineering", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_02", title: "Executive Leadership Team Sync", expectedCategory: "D", expectedSubtype: "int.leadership_sync", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_03", title: "Annual Performance Review — Head of Product", expectedCategory: "D", expectedSubtype: "int.performance_review", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_04", title: "Difficult Feedback Discussion", expectedCategory: "D", expectedSubtype: "int.difficult_conversation", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_05", title: "Candidate Interview — Chief Marketing Officer", expectedCategory: "D", expectedSubtype: "int.candidate_interview", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_06", title: "Skip-level 1:1 with Senior Engineers", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_07", title: "Confidential Compensation Discussion", expectedCategory: "D", expectedSubtype: "int.difficult_conversation", difficulty: "ambiguous", categoryGroup: "people" },
  { id: "gold_d_08", title: "Hiring Culture Fit Interview", expectedCategory: "D", expectedSubtype: "int.candidate_interview", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_09", title: "Exit Interview & Transition Plan", expectedCategory: "D", expectedSubtype: "int.difficult_conversation", difficulty: "ambiguous", categoryGroup: "people" },
  { id: "gold_d_10", title: "1-on-1 Catchup with Chief of Staff", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_11", title: "Director Performance Evaluation", expectedCategory: "D", expectedSubtype: "int.performance_review", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_12", title: "Executive Talent Review", expectedCategory: "D", expectedSubtype: "int.leadership_sync", difficulty: "ambiguous", categoryGroup: "people" },
  { id: "gold_d_13", title: "Sensitive Team Restructuring Discussion", expectedCategory: "D", expectedSubtype: "int.difficult_conversation", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_14", title: "Weekly 1:1 with Chief Operating Officer", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_15", title: "Final Round Interview: Head of Growth", expectedCategory: "D", expectedSubtype: "int.candidate_interview", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_16", title: "Peer 360 Feedback Debrief", expectedCategory: "D", expectedSubtype: "int.performance_review", difficulty: "ambiguous", categoryGroup: "people" },
  { id: "gold_d_17", title: "Promotion & Career Development Check-in", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "ambiguous", categoryGroup: "people" },
  { id: "gold_d_18", title: "Executive Team Alignment Meeting", expectedCategory: "D", expectedSubtype: "int.leadership_sync", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_19", title: "Probation Review Discussion", expectedCategory: "D", expectedSubtype: "int.performance_review", difficulty: "obvious", categoryGroup: "people" },
  { id: "gold_d_20", title: "Co-founder Alignment Session", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "ambiguous", categoryGroup: "people" },

  // ── CATEGORY E: Strategic Thinking & Decision Making (20 cases) ──────
  { id: "gold_e_01", title: "Deep work block — strategy memo", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_02", title: "Weekly AI Forum", expectedCategory: "E", expectedSubtype: "str.community", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_03", title: "Chief AI Thursday connects", expectedCategory: "E", expectedSubtype: "str.community", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_04", title: "Product Architecture Review", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_05", title: "Focus Time: Strategic Whitepaper Writing", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_06", title: "Competitor Moat & Positioning Analysis", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "ambiguous", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_07", title: "Executive Coaching Session with Marshall", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_08", title: "Deep Thinking: 2027 Horizon Roadmap", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_09", title: "Design Sprint Review — Core User Flow", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_10", title: "Founders Mastermind Breakfast", expectedCategory: "E", expectedSubtype: "str.community", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_11", title: "Self Mastery Learning Lab", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_12", title: "Uninterrupted Focus Time: Board Deck Prep", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "misleading_title", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_13", title: "Strategy Brainstorming with Advisors", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "ambiguous", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_14", title: "AI Prompt Engineering Masterclass", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_15", title: "Technical Spec Architecture Deep Dive", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_16", title: "Focus Block: Model Evaluation Analysis", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_17", title: "YPO Forum Monthly Session", expectedCategory: "E", expectedSubtype: "str.community", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_18", title: "Scientific Advisory Working Session", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "ambiguous", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_19", title: "Quiet Time: Business Model Canvas Refinement", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "obvious", categoryGroup: "strategy_deep_work" },
  { id: "gold_e_20", title: "Cognitive Science Seminar", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "obvious", categoryGroup: "strategy_deep_work" },

  // ── CATEGORY F: Conferences & External Events (20 cases) ─────────────
  { id: "gold_f_01", title: "Queen's Gate School open evening", expectedCategory: "F", expectedSubtype: "conf.workshop", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_02", title: "Attending SaaStr Annual 2026", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_03", title: "Tech Ecosystem Networking Drinks", expectedCategory: "F", expectedSubtype: "conf.networking", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_04", title: "London EdTech Summit Attendee", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_05", title: "National Education Exhibition Expo", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_06", title: "Annual Leadership Awards Gala Dinner", expectedCategory: "F", expectedSubtype: "conf.award", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_07", title: "Industry Trade Fair & Partner Showcase", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_08", title: "Founder Alumni Reunion Mixer", expectedCategory: "F", expectedSubtype: "conf.networking", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_09", title: "Slush Helsinki Conference Floor", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_10", title: "HealthTech Innovation Showcase", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_11", title: "Charity Foundation Annual Benefit Evening", expectedCategory: "F", expectedSubtype: "conf.award", difficulty: "ambiguous", categoryGroup: "conference" },
  { id: "gold_f_12", title: "Investor & Founder Networking Cocktail", expectedCategory: "F", expectedSubtype: "conf.networking", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_13", title: "Executive Offsite Workshop", expectedCategory: "F", expectedSubtype: "conf.offsite", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_14", title: "Customer Success Summit", expectedCategory: "F", expectedSubtype: "conf.customer_summit", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_15", title: "Global AI Convention — Day 2", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_16", title: "Oxford Union Evening Debate", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "ambiguous", categoryGroup: "conference" },
  { id: "gold_f_17", title: "Venture Capital Partner Showcase", expectedCategory: "F", expectedSubtype: "conf.networking", difficulty: "ambiguous", categoryGroup: "conference" },
  { id: "gold_f_18", title: "Design Museum Private Exhibition Tour", expectedCategory: "F", expectedSubtype: "conf.attendance", difficulty: "ambiguous", categoryGroup: "conference" },
  { id: "gold_f_19", title: "Innovation Awards Ceremony", expectedCategory: "F", expectedSubtype: "conf.award", difficulty: "obvious", categoryGroup: "conference" },
  { id: "gold_f_20", title: "Senior Leadership Team Offsite — Day 1", expectedCategory: "F", expectedSubtype: "conf.offsite", difficulty: "obvious", categoryGroup: "conference" },

  // ── CATEGORY G: Travel (20 cases) ────────────────────────────────────
  { id: "gold_g_01", title: "Flight to New York (BA 183)", expectedCategory: "G", expectedSubtype: "trv.flight", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_02", title: "Stay: DoubleTree by Hilton", expectedCategory: "G", expectedSubtype: "trv.accommodation", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_03", title: "Statue of Liberty and Ellis Island tour", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_04", title: "Statue of Liberty and Elise Island New York", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_05", title: "Day trip to the Hamptons", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_06", title: "Heathrow Express to Paddington", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_07", title: "Long-haul flight: LHR → SIN (SQ 317)", expectedCategory: "G", expectedSubtype: "trv.long_haul", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_08", title: "Hotel Check-in: The Carlyle NYC", expectedCategory: "G", expectedSubtype: "trv.accommodation", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_09", title: "Eurostar London to Paris", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_10", title: "Flight: JFK to SFO (DL 455)", expectedCategory: "G", expectedSubtype: "trv.flight", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_11", title: "Airbnb reservation in Cotswolds", expectedCategory: "G", expectedSubtype: "trv.accommodation", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_12", title: "Transit through Dubai International Airport", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_13", title: "Return Flight: SFO to LHR", expectedCategory: "G", expectedSubtype: "trv.long_haul", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_14", title: "Airport Security & Boarding Gate", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_15", title: "Reservation at Four Seasons Geneva", expectedCategory: "G", expectedSubtype: "trv.accommodation", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_16", title: "Train to Manchester Piccadilly", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_17", title: "Flight to Zurich (LX 319)", expectedCategory: "G", expectedSubtype: "trv.flight", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_18", title: "Car Rental Pickup at SFO", expectedCategory: "G", expectedSubtype: "trv.travel_day", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_19", title: "Marriott Marquis Times Square stay", expectedCategory: "G", expectedSubtype: "trv.accommodation", difficulty: "obvious", categoryGroup: "travel" },
  { id: "gold_g_20", title: "Red-eye Flight: LAX to JFK", expectedCategory: "G", expectedSubtype: "trv.long_haul", difficulty: "obvious", categoryGroup: "travel" },

  // ── CATEGORY H: Personal Time & Recovery (20 cases) ──────────────────
  { id: "gold_h_01", title: "1 day liquid fast", expectedCategory: "H", expectedSubtype: "rhy.wellness_self_care", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_02", title: "National Day", expectedCategory: "H", expectedSubtype: "rhy.holiday", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_03", title: "Reservation at Yoshoku", expectedCategory: "H", expectedSubtype: "rhy.social", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_04", title: "Dentist Appointment — Routine Checkup", expectedCategory: "H", expectedSubtype: "rhy.wellness_health_check", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_05", title: "Morning Gym: Strength & Mobility", expectedCategory: "H", expectedSubtype: "rhy.wellness_fitness", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_06", title: "Family Sunday Roast", expectedCategory: "H", expectedSubtype: "rhy.social", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_07", title: "Annual Physical Exam & Bloodwork", expectedCategory: "H", expectedSubtype: "rhy.wellness_health_check", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_08", title: "Bank Holiday Monday", expectedCategory: "H", expectedSubtype: "rhy.holiday", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_09", title: "Physiotherapy Session", expectedCategory: "H", expectedSubtype: "rhy.wellness_self_care", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_10", title: "Dinner with Sarah & Tom", expectedCategory: "H", expectedSubtype: "rhy.social", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_11", title: "Deep Tissue Massage Recovery", expectedCategory: "H", expectedSubtype: "rhy.wellness_self_care", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_12", title: "School Pick-up & Kids Football", expectedCategory: "H", expectedSubtype: "rhy.social", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_13", title: "Quiet Evening Shutdown", expectedCategory: "H", expectedSubtype: "rhy.wellness_self_care", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_14", title: "Yoga & Breathwork Class", expectedCategory: "H", expectedSubtype: "rhy.wellness_fitness", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_15", title: "Optician Eye Test", expectedCategory: "H", expectedSubtype: "rhy.wellness_health_check", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_16", title: "Personal PTO — Family Day", expectedCategory: "H", expectedSubtype: "rhy.holiday", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_17", title: "Brunch with University Friends", expectedCategory: "H", expectedSubtype: "rhy.social", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_18", title: "Cardio Zone 2 Run", expectedCategory: "H", expectedSubtype: "rhy.wellness_fitness", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_19", title: "Meditation & Cold Plunge Reset", expectedCategory: "H", expectedSubtype: "rhy.wellness_self_care", difficulty: "obvious", categoryGroup: "personal" },
  { id: "gold_h_20", title: "Christmas Day Holiday", expectedCategory: "H", expectedSubtype: "rhy.holiday", difficulty: "obvious", categoryGroup: "personal" },

  // ── CATEGORY I: Operations & Execution (25 cases) ────────────────────
  { id: "gold_i_01", title: "Weekly team sync", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_02", title: "Monday Morning Operations Review", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_03", title: "Daily Engineering Standup", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_04", title: "Weekly Business Review (WBR) — KPIs", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_05", title: "Admin Block — Approvals & Invoicing", expectedCategory: "I", expectedSubtype: "ops.admin", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_06", title: "Sprint Planning & Backlog Grooming", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_07", title: "SOC2 Compliance Audit Check-in", expectedCategory: "I", expectedSubtype: "str.compliance", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_08", title: "Product Launch Go/No-Go Readiness", expectedCategory: "I", expectedSubtype: "str.product_launch", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_09", title: "Bi-weekly Operations Check-in", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_10", title: "Revenue Pipeline & Sales Ops Review", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_11", title: "Inbox Zero & Contract Signatures", expectedCategory: "I", expectedSubtype: "ops.admin", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_12", title: "Bi-weekly Product Sprint Retro", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_13", title: "ISO 27001 Annual Recertification Review", expectedCategory: "I", expectedSubtype: "str.compliance", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_14", title: "Feature Release Coordination Sync", expectedCategory: "I", expectedSubtype: "str.product_launch", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_15", title: "Weekly Standup — Customer Support", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_16", title: "Finance & Accounts Payable Approvals", expectedCategory: "I", expectedSubtype: "ops.admin", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_17", title: "Monthly OKR & Milestone Progress Review", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_18", title: "GDPR Data Processing Agreement Audit", expectedCategory: "I", expectedSubtype: "str.compliance", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_19", title: "Mobile App Store Release Deployment", expectedCategory: "I", expectedSubtype: "str.product_launch", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_20", title: "Quarterly Operating Plan Tracking", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_21", title: "Weekly Ops Huddle", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_22", title: "Timesheet & Expense Report Approvals", expectedCategory: "I", expectedSubtype: "ops.admin", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_23", title: "Commercial Legal Compliance Signoff", expectedCategory: "I", expectedSubtype: "str.compliance", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_24", title: "Beta Launch Readiness Review", expectedCategory: "I", expectedSubtype: "str.product_launch", difficulty: "obvious", categoryGroup: "operations" },
  { id: "gold_i_25", title: "Weekly Metrics Dashboard Walkthrough", expectedCategory: "I", expectedSubtype: "ops.operating_review", difficulty: "obvious", categoryGroup: "operations" },

  // ── CATEGORY J: Crisis, Risk & Incidents (20 cases) ──────────────────
  { id: "gold_j_01", title: "Production incident escalation", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_02", title: "URGENT: Cloud Database Outage War Room", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_03", title: "Security Breach Post-Mortem & Incident Review", expectedCategory: "J", expectedSubtype: "risk.incident_review", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_04", title: "Emergency Meeting with Legal Counsel — Patent Dispute", expectedCategory: "J", expectedSubtype: "risk.legal_regulatory", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_05", title: "PR Crisis Holding Statement & Communications Response", expectedCategory: "J", expectedSubtype: "risk.reputation", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_06", title: "Critical Sev-1 Incident Response Call", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_07", title: "Post-Incident Debrief — Payment Gateway Failure", expectedCategory: "J", expectedSubtype: "risk.incident_review", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_08", title: "Regulatory Investigation Urgent Response", expectedCategory: "J", expectedSubtype: "risk.legal_regulatory", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_09", title: "Press Crisis Containment Discussion", expectedCategory: "J", expectedSubtype: "risk.reputation", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_10", title: "Emergency Board Incident Briefing", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "ambiguous", categoryGroup: "crisis_risk" },
  { id: "gold_j_11", title: "Ransomware Threat Triage & Incident Command", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_12", title: "Root Cause Analysis: Service Degradation", expectedCategory: "J", expectedSubtype: "risk.incident_review", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_13", title: "Subpoena Response & Outside Legal Advice", expectedCategory: "J", expectedSubtype: "risk.legal_regulatory", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_14", title: "Social Media Controversy Response Plan", expectedCategory: "J", expectedSubtype: "risk.reputation", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_15", title: "War Room: Zero-Day Vulnerability Patching", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_16", title: "Infrastructure Failure Blameless Postmortem", expectedCategory: "J", expectedSubtype: "risk.incident_review", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_17", title: "Emergency Employment Dispute Settlement", expectedCategory: "J", expectedSubtype: "risk.legal_regulatory", difficulty: "ambiguous", categoryGroup: "crisis_risk" },
  { id: "gold_j_18", title: "Reputational Risk Review — Leak Investigation", expectedCategory: "J", expectedSubtype: "risk.reputation", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_19", title: "Critical Infrastructure War Room", expectedCategory: "J", expectedSubtype: "gov.crisis", difficulty: "obvious", categoryGroup: "crisis_risk" },
  { id: "gold_j_20", title: "Incident Retrospective: Data Pipeline Corrupted", expectedCategory: "J", expectedSubtype: "risk.incident_review", difficulty: "obvious", categoryGroup: "crisis_risk" },

  // ── MISLEADING TITLES & EDGE CASES (15 cases) ────────────────────────
  { id: "gold_edge_01", title: "Board Strategy Memo Draft", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Writing board memo alone is deep work, not board meeting" },
  { id: "gold_edge_02", title: "Prep for Q3 Board Meeting", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Prep for board supports E, not A" },
  { id: "gold_edge_03", title: "Statue of Liberty Strategy Offsite", expectedCategory: "A", expectedSubtype: "str.strategy_planning", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Venue contains Statue of Liberty, but topic is governance strategy" },
  { id: "gold_edge_04", title: "Weekly ops sync: urgent review items", expectedCategory: "I", expectedSubtype: "rhy.catchup", difficulty: "edge_case", categoryGroup: "cross_check", notes: "Urgent in recurring sync stays I unless incident war room" },
  { id: "gold_edge_05", title: "Flight Simulator Demonstration", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Demonstration of product, not real travel flight" },
  { id: "gold_edge_06", title: "Conference room booking for 1:1", expectedCategory: "D", expectedSubtype: "int.one_on_one", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Conference room is a room, meeting is 1:1" },
  { id: "gold_edge_07", title: "Keynote presentation prep time", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Solo prep for keynote is deep work" },
  { id: "gold_edge_08", title: "Client dinner after demo", expectedCategory: "B", expectedSubtype: "inf.client_presentation", difficulty: "ambiguous", categoryGroup: "cross_check", notes: "Commercial relationship dinner outranks social" },
  { id: "gold_edge_09", title: "Travel expense review with CFO", expectedCategory: "I", expectedSubtype: "ops.admin", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Reviewing expenses is operational admin, not travel" },
  { id: "gold_edge_10", title: "Emergency dental surgery", expectedCategory: "H", expectedSubtype: "rhy.wellness_health_check", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Emergency health is recovery H, not J crisis" },
  { id: "gold_edge_11", title: "Media training for upcoming TV interview", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Media coaching is learning E, not live speaking C" },
  { id: "gold_edge_12", title: "Investor pitch rehearsal with team", expectedCategory: "E", expectedSubtype: "str.review", difficulty: "ambiguous", categoryGroup: "cross_check", notes: "Internal rehearsal is review E, not live investor pitch B" },
  { id: "gold_edge_13", title: "Hotel ballroom walkthrough for Gala", expectedCategory: "F", expectedSubtype: "conf.award", difficulty: "ambiguous", categoryGroup: "cross_check", notes: "Event venue walkthrough is event prep F" },
  { id: "gold_edge_14", title: "Crisis Management Training Workshop", expectedCategory: "E", expectedSubtype: "str.learning", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Training workshop is learning E, not actual crisis J" },
  { id: "gold_edge_15", title: "Airport lounge deep work block", expectedCategory: "E", expectedSubtype: "str.deep_work", difficulty: "misleading_title", categoryGroup: "cross_check", notes: "Deep work at airport is cognitive work E" },
];
