// Holdout Set: N=50 hand-labelled events (5 per category across all 10 categories A–J).
// Spec §14, Stage D Step 17:
// "A further 50 or so are kept aside as a holdout. They are never looked at while tuning,
// and scored only to confirm the result."

import type { EventCategoryId } from "./event-categories.ts";

export interface HoldoutEventCase {
  id: string;
  title: string;
  description?: string | null;
  attendees?: Array<{
    name?: string | null;
    email?: string | null;
    domain?: string | null;
    isSelf?: boolean;
    isOrganizer?: boolean;
  }>;
  location?: string | null;
  durationMinutes?: number | null;
  isRecurring?: boolean;
  expectedCategory: EventCategoryId;
  expectedSubtype?: string | null;
  difficulty: "obvious" | "ambiguous" | "misleading_title" | "edge_case";
  categoryGroup: string;
  notes?: string;
}

export const HOLDOUT_SET: HoldoutEventCase[] = [
  // ── CATEGORY A: Board & Governance (5 cases) ─────────────────────────
  {
    id: "hold_a_01",
    title: "Supervisory Board Semi-Annual Conclave",
    expectedCategory: "A",
    expectedSubtype: "gov.board_meeting",
    difficulty: "obvious",
    categoryGroup: "governance",
    notes: "Formal supervisory board governance session",
  },
  {
    id: "hold_a_02",
    title: "Compensation & ESG Oversight Committee",
    expectedCategory: "A",
    expectedSubtype: "gov.committee",
    difficulty: "obvious",
    categoryGroup: "governance",
    notes: "Board sub-committee review",
  },
  {
    id: "hold_a_03",
    title: "Extraordinary General Meeting of Shareholders",
    expectedCategory: "A",
    expectedSubtype: "gov.agm",
    difficulty: "obvious",
    categoryGroup: "governance",
    notes: "Shareholder governance assembly",
  },
  {
    id: "hold_a_04",
    title: "Board Trustee Strategic Alignment Session",
    expectedCategory: "A",
    expectedSubtype: "gov.board_meeting",
    difficulty: "ambiguous",
    categoryGroup: "governance",
    notes: "Trustee board session",
  },
  {
    id: "hold_a_05",
    title: "10-Year Corporate Strategy Planning",
    expectedCategory: "A",
    expectedSubtype: "str.strategy_planning",
    difficulty: "ambiguous",
    categoryGroup: "governance",
    notes: "Long-term strategy planning stays in Category A",
  },

  // ── CATEGORY B: Pitches, Deals & Negotiations (5 cases) ───────────────
  {
    id: "hold_b_01",
    title: "Enterprise SaaS Renewal Terms & Pricing",
    expectedCategory: "B",
    expectedSubtype: "inf.commercial_negotiation",
    difficulty: "obvious",
    categoryGroup: "pitch_deal",
    notes: "Commercial pricing negotiation",
  },
  {
    id: "hold_b_02",
    title: "Series Seed Pitch: Founders Fund",
    expectedCategory: "B",
    expectedSubtype: "inf.pitch",
    difficulty: "obvious",
    categoryGroup: "pitch_deal",
    notes: "Venture investor pitch",
  },
  {
    id: "hold_b_03",
    title: "Prospective Client Platform Demonstration",
    expectedCategory: "B",
    expectedSubtype: "inf.client_presentation",
    difficulty: "obvious",
    categoryGroup: "pitch_deal",
    notes: "Sales demo for prospective customer",
  },
  {
    id: "hold_b_04",
    title: "Global Distribution Partnership Term Sheet",
    expectedCategory: "B",
    expectedSubtype: "inf.partnership",
    difficulty: "obvious",
    categoryGroup: "pitch_deal",
    notes: "Commercial partnership agreement",
  },
  {
    id: "hold_b_05",
    title: "Vendor RFP Contract Closing Negotiation",
    expectedCategory: "B",
    expectedSubtype: "inf.commercial_negotiation",
    difficulty: "ambiguous",
    categoryGroup: "pitch_deal",
    notes: "Contract closing and procurement negotiation",
  },

  // ── CATEGORY C: High-Stakes Visibility & Public Presentations (5 cases)
  {
    id: "hold_c_01",
    title: "Global Fintech Summit Opening Keynote Address",
    expectedCategory: "C",
    expectedSubtype: "vis.keynote",
    difficulty: "obvious",
    categoryGroup: "visibility",
    notes: "Major public keynote delivery",
  },
  {
    id: "hold_c_02",
    title: "Q4 Company-Wide All Hands & Vision",
    expectedCategory: "C",
    expectedSubtype: "vis.all_hands",
    difficulty: "obvious",
    categoryGroup: "visibility",
    notes: "Internal all-hands company presentation",
  },
  {
    id: "hold_c_03",
    title: "Media Press Conference: Product Launch",
    expectedCategory: "C",
    expectedSubtype: "vis.press",
    difficulty: "obvious",
    categoryGroup: "visibility",
    notes: "Press conference announcing major launch",
  },
  {
    id: "hold_c_04",
    title: "FT Live Executive Interview on AI Future",
    expectedCategory: "C",
    expectedSubtype: "vis.media_interview",
    difficulty: "ambiguous",
    categoryGroup: "visibility",
    notes: "Broadcast executive media interview",
  },
  {
    id: "hold_c_05",
    title: "Industry Leaders Executive Roundtable on AI Safety",
    expectedCategory: "C",
    expectedSubtype: "vis.roundtable",
    difficulty: "ambiguous",
    categoryGroup: "visibility",
    notes: "High-visibility leadership roundtable",
  },

  // ── CATEGORY D: 1:1s, Team Leadership & Performance (5 cases) ─────────
  {
    id: "hold_d_01",
    title: "Sarah Jenkins / Manoj Kumar Bi-weekly 1:1",
    expectedCategory: "D",
    expectedSubtype: "lead.executive_1on1",
    difficulty: "obvious",
    categoryGroup: "leadership",
    notes: "Connector two-party executive 1:1",
  },
  {
    id: "hold_d_02",
    title: "Engineering Director Annual Performance Review",
    expectedCategory: "D",
    expectedSubtype: "lead.performance_review",
    difficulty: "obvious",
    categoryGroup: "leadership",
    notes: "Formal annual evaluation",
  },
  {
    id: "hold_d_03",
    title: "VP Marketing Career Growth & Promotion Checkpoint",
    expectedCategory: "D",
    expectedSubtype: "lead.mentoring",
    difficulty: "ambiguous",
    categoryGroup: "leadership",
    notes: "Career development and mentoring session",
  },
  {
    id: "hold_d_04",
    title: "Skip-level Mentorship Coffee: Alex",
    expectedCategory: "D",
    expectedSubtype: "lead.mentoring",
    difficulty: "ambiguous",
    categoryGroup: "leadership",
    notes: "Skip-level 1:1 development conversation",
  },
  {
    id: "hold_d_05",
    title: "Direct Report OKR Alignment & Compensation Feedback",
    expectedCategory: "D",
    expectedSubtype: "lead.performance_review",
    difficulty: "ambiguous",
    categoryGroup: "leadership",
    notes: "Performance & compensation discussion with direct report",
  },

  // ── CATEGORY E: Strategy, Advisory, Learning & Deep Work (5 cases) ────
  {
    id: "hold_e_01",
    title: "Solo Deep Work: Q1 Product Roadmap Architecture",
    expectedCategory: "E",
    expectedSubtype: "str.deep_work",
    difficulty: "obvious",
    categoryGroup: "strategy_deep",
    notes: "Uninterrupted deep work block",
  },
  {
    id: "hold_e_02",
    title: "Focus Time: Competitor Defensive Moat Deep Dive",
    expectedCategory: "E",
    expectedSubtype: "str.review",
    difficulty: "misleading_title",
    categoryGroup: "strategy_deep",
    notes: "Strategic review and competitive moat deep dive",
  },
  {
    id: "hold_e_03",
    title: "Advisory Board Working Group Session",
    expectedCategory: "E",
    expectedSubtype: "str.review",
    difficulty: "ambiguous",
    categoryGroup: "strategy_deep",
    notes: "Working session advisory context",
  },
  {
    id: "hold_e_04",
    title: "Masterclass: Executive Decision Making Under Uncertainty",
    expectedCategory: "E",
    expectedSubtype: "str.learning",
    difficulty: "obvious",
    categoryGroup: "strategy_deep",
    notes: "Professional development masterclass",
  },
  {
    id: "hold_e_05",
    title: "Deep Work Block: Strategic Monograph Drafting",
    expectedCategory: "E",
    expectedSubtype: "str.deep_work",
    difficulty: "obvious",
    categoryGroup: "strategy_deep",
    notes: "Solo writing and deep concentration",
  },

  // ── CATEGORY F: External Collaboration, Workshops & Conferences (5) ──
  {
    id: "hold_f_01",
    title: "SaaStr Annual 2026 Conference Day 1",
    expectedCategory: "F",
    expectedSubtype: "conf.customer_summit",
    difficulty: "obvious",
    categoryGroup: "external_collab",
    notes: "Industry conference attendance",
  },
  {
    id: "hold_f_02",
    title: "Product Leadership Cross-Company Offsite",
    expectedCategory: "F",
    expectedSubtype: "conf.offsite",
    difficulty: "obvious",
    categoryGroup: "external_collab",
    notes: "Collaborative offsite workshop",
  },
  {
    id: "hold_f_03",
    title: "Design Sprint: Multi-Tenant Architecture Workshop",
    expectedCategory: "F",
    expectedSubtype: "conf.offsite",
    difficulty: "ambiguous",
    categoryGroup: "external_collab",
    notes: "Interactive architecture workshop",
  },
  {
    id: "hold_f_04",
    title: "Tech Founders Networking Reception & Mixer",
    expectedCategory: "F",
    expectedSubtype: "conf.networking",
    difficulty: "obvious",
    categoryGroup: "external_collab",
    notes: "Professional ecosystem networking reception",
  },
  {
    id: "hold_f_05",
    title: "Annual Industry Excellence Awards Gala Dinner",
    expectedCategory: "F",
    expectedSubtype: "conf.award",
    difficulty: "ambiguous",
    categoryGroup: "external_collab",
    notes: "Awards gala ceremony",
  },

  // ── CATEGORY G: Travel, Logistics & Buffers (5 cases) ─────────────────
  {
    id: "hold_g_01",
    title: "Flight BA178: JFK to LHR",
    expectedCategory: "G",
    expectedSubtype: "trv.flight",
    difficulty: "obvious",
    categoryGroup: "travel",
    notes: "Commercial airline flight",
  },
  {
    id: "hold_g_02",
    title: "Eurostar Train 9014: London St Pancras to Paris Gare du Nord",
    expectedCategory: "G",
    expectedSubtype: "trv.travel_day",
    difficulty: "obvious",
    categoryGroup: "travel",
    notes: "High-speed rail journey",
  },
  {
    id: "hold_g_03",
    title: "Heathrow Express Transit to Airport",
    expectedCategory: "G",
    expectedSubtype: "trv.travel_day",
    difficulty: "obvious",
    categoryGroup: "travel",
    notes: "Airport train transfer",
  },
  {
    id: "hold_g_04",
    title: "The Savoy London Hotel Reservation & Check-in",
    expectedCategory: "G",
    expectedSubtype: "trv.accommodation",
    difficulty: "ambiguous",
    categoryGroup: "travel",
    notes: "Hotel lodging check-in",
  },
  {
    id: "hold_g_05",
    title: "San Francisco to Tokyo Long Haul Flight NH007",
    expectedCategory: "G",
    expectedSubtype: "trv.long_haul",
    difficulty: "obvious",
    categoryGroup: "travel",
    notes: "Transpacific flight",
  },

  // ── CATEGORY H: Renewal, Health, Family & Recreation (5 cases) ────────
  {
    id: "hold_h_01",
    title: "Comprehensive Executive Health & Biomarker Screening",
    expectedCategory: "H",
    expectedSubtype: "rhy.wellness_health_check",
    difficulty: "obvious",
    categoryGroup: "renewal",
    notes: "Clinical health assessment",
  },
  {
    id: "hold_h_02",
    title: "Morning Marathon Training 10k Run",
    expectedCategory: "H",
    expectedSubtype: "rhy.wellness_fitness",
    difficulty: "obvious",
    categoryGroup: "renewal",
    notes: "Cardio workout block",
  },
  {
    id: "hold_h_03",
    title: "Family Weekend: Leo's Soccer Championship",
    expectedCategory: "H",
    expectedSubtype: "rhy.family_milestone",
    difficulty: "obvious",
    categoryGroup: "renewal",
    notes: "Family milestone activity",
  },
  {
    id: "hold_h_04",
    title: "Symphony Orchestra Concert Evening",
    expectedCategory: "H",
    expectedSubtype: "rhy.cultural_arts",
    difficulty: "ambiguous",
    categoryGroup: "renewal",
    notes: "Recreational arts evening",
  },
  {
    id: "hold_h_05",
    title: "Mindfulness & Deep Breathwork Meditation",
    expectedCategory: "H",
    expectedSubtype: "rhy.wellness_self_care",
    difficulty: "obvious",
    categoryGroup: "renewal",
    notes: "Mental restorative self-care",
  },

  // ── CATEGORY I: Operations, Execution & Rhythms (5 cases) ─────────────
  {
    id: "hold_i_01",
    title: "Weekly Cross-Functional Operating Review",
    expectedCategory: "I",
    expectedSubtype: "ops.operating_review",
    difficulty: "obvious",
    categoryGroup: "operations",
    notes: "Standard weekly operating review",
  },
  {
    id: "hold_i_02",
    title: "Sprint Planning & Backlog Grooming Rhythm",
    expectedCategory: "I",
    expectedSubtype: "ops.operating_review",
    difficulty: "obvious",
    categoryGroup: "operations",
    notes: "Agile operational sprint planning",
  },
  {
    id: "hold_i_03",
    title: "Weekly Team Sync & Tactical Status Check-in",
    expectedCategory: "I",
    expectedSubtype: "rhy.catchup",
    difficulty: "obvious",
    categoryGroup: "operations",
    notes: "Routine internal team tactical sync",
  },
  {
    id: "hold_i_04",
    title: "Monthly Financial Close & P&L Signoff Review",
    expectedCategory: "I",
    expectedSubtype: "ops.operating_review",
    difficulty: "ambiguous",
    categoryGroup: "operations",
    notes: "Operational finance rhythm",
  },
  {
    id: "hold_i_05",
    title: "Admin: Expensify Processing & Calendar Housekeeping",
    expectedCategory: "I",
    expectedSubtype: "ops.admin",
    difficulty: "obvious",
    categoryGroup: "operations",
    notes: "Administrative logistics and operational chores",
  },

  // ── CATEGORY J: Crises, Incidents & High-Urgency Disruptions (5 cases) ─
  {
    id: "hold_j_01",
    title: "SEV-1 Production Database Outage War Room",
    expectedCategory: "J",
    expectedSubtype: "risk.incident_review",
    difficulty: "obvious",
    categoryGroup: "crisis",
    notes: "Critical infrastructure emergency outage",
  },
  {
    id: "hold_j_02",
    title: "Urgent GDPR Data Privacy Breach Response Bridge",
    expectedCategory: "J",
    expectedSubtype: "risk.legal_regulatory",
    difficulty: "obvious",
    categoryGroup: "crisis",
    notes: "High-urgency data breach legal & tech response",
  },
  {
    id: "hold_j_03",
    title: "Hostile Takeover Defence — Urgent Legal Briefing",
    expectedCategory: "J",
    expectedSubtype: "risk.legal_regulatory",
    difficulty: "ambiguous",
    categoryGroup: "crisis",
    notes: "Existential legal/regulatory emergency",
  },
  {
    id: "hold_j_04",
    title: "Emergency Crisis PR: Reputational Leak Mitigation",
    expectedCategory: "J",
    expectedSubtype: "risk.reputation",
    difficulty: "obvious",
    categoryGroup: "crisis",
    notes: "Reputational crisis containment bridge",
  },
  {
    id: "hold_j_05",
    title: "Major Supply Chain Disruption Emergency Executive Sync",
    expectedCategory: "J",
    expectedSubtype: "risk.incident_review",
    difficulty: "ambiguous",
    categoryGroup: "crisis",
    notes: "Urgent disruption operational incident",
  },
];
